/* Transition Life / Home & Beyond: visual rooms, touch placement and the existing town economy. */
(function(){'use strict';
const C=TTLifeCatalog,K=TTLifeCore,S=TTLifeStore,host=document.getElementById('lifeApp'),dialog=document.getElementById('lifeDialog'),body=document.getElementById('dialogBody');
const captured=S.name(),isStore=document.body.dataset.lifePage==='store';let shopScene='exterior',room='living',placing=null,compare=[],cookTask=null,actionTimer=null,toastTimer;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cash=n=>'$'+Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const btn=(label,act,id='',cls='')=>'<button class="'+cls+'" data-act="'+act+'" data-id="'+esc(id)+'">'+label+'</button>';
const link=(label,url,cls='')=>'<a class="link '+cls+'" href="'+url+'">'+label+'</a>';
function state(){const w=S.read(),r=w.residents[captured];if(!r)throw Error('Choose your resident in Transition Town first.');return {w,r,l:K.init(r)};}
function change(fn){const result=S.change(fn,captured);updateHUD();return result;}
function toast(text){clearTimeout(toastTimer);let el=document.getElementById('lifeToast');el.textContent=text;el.className='show';toastTimer=setTimeout(()=>el.className='',5500);}
function close(){dialog.close();if(actionTimer){clearInterval(actionTimer);actionTimer=null;}cookTask=null;}
function modal(title,html){if(actionTimer){clearInterval(actionTimer);actionTimer=null;}body.innerHTML='<h2 id="dialogTitle">'+esc(title)+'</h2>'+html;if(!dialog.open)dialog.showModal();body.scrollTop=0;}
function shell(content){const {r,l}=state();host.innerHTML=(S.sandbox()?'<div class="test-banner">MISS KAYLA TEST MODE · Changes stay in this practice copy. '+btn('Exit test mode','test-exit')+'</div>':'')+'<header class="topbar"><a href="transition-town.html">← Town</a><div class="brand"><small>TRANSITION TOWN</small>'+(isStore?'Home & Beyond':'Transition Life')+'</div><div class="identity"><span>'+esc(captured)+(S.sandbox()?' · Practice':'')+'<br><span id="simDate">'+esc(l.date)+'</span> · simulation day</span><strong id="balance">'+cash(r.checking)+'</strong></div></header><nav class="life-nav" aria-label="Transition Life">'+link('My home','transition-life.html',!isStore?'primary':'')+link('Home & Beyond','home-beyond.html',isStore?'primary':'')+btn('Move-in guide','guide')+btn('Inventory & deliveries','inventory')+btn('Bills & utilities','bills')+link('Grocery store','grocery-store.html')+link('Park','transition-town.html?life=park')+link('Go to work','transition-town.html?life=jobs')+link('Bank','transition-town.html?life=bank')+(S.teacher(captured)?btn('Miss Kayla overview','teacher','', 'gold'):'')+'</nav><div class="needs" id="needs"></div>'+content+'<footer class="footer-note">One resident. One Transition Town balance. Progress is saved on this device. All money and bills are fictional classroom practice.</footer>';updateHUD();}
function updateHUD(){try{const {r,l}=state();let bal=document.getElementById('balance');if(bal)bal.textContent=cash(r.checking);let d=document.getElementById('simDate');if(d)d.textContent=l.date;let n=document.getElementById('needs');if(n)n.innerHTML=Object.entries(l.needs).map(([key,v])=>'<div class="need">'+key+'<span>'+Math.round(v)+'%</span><meter aria-label="'+key+'" min="0" max="100" low="25" high="75" optimum="100" value="'+v+'">'+Math.round(v)+'</meter></div>').join('');}catch(e){}}
function render(){if(isStore)renderStore();else renderHome();}
// Tight source rectangles keep the coordinated furniture illustrations whole at any touch size.
const spriteRects={bed:[5,108,395,275],frame:[5,108,395,275],couch:[406,76,400,300],table:[813,80,345,302],dining:[813,80,345,302],chair:[1180,66,262,335],dresser:[30,407,383,307],lamp:[518,374,191,350],tv:[769,445,367,298],console:[1164,440,280,290],rug:[10,794,520,245],art:[546,724,253,315],mirror:[546,724,253,315],vacuum:[895,698,210,340],supplies:[1156,802,276,232]};
const essentials={sheets:[20,16,351,271],pillow:[385,15,345,275],blanket:[735,33,347,237],towel:[1124,40,300,245],washcloth:[1124,40,300,245],plate:[20,300,335,230],bowl:[408,312,282,225],cup:[793,300,231,242],silverware:[1112,290,306,259],pan:[23,531,363,251],cookware:[402,533,322,243],pot:[402,533,322,243],utensils:[773,534,260,250],containers:[1114,526,310,266],basket:[20,789,360,269],hygiene:[438,780,271,278],'trash-bags':[768,780,292,280],cleaner:[1144,780,251,280],detergent:[1144,780,251,280]};
function art(p){const essential=essentials[p.kind]||p.tags?.map(t=>essentials[t]).find(Boolean);const box=essential||spriteRects[p.kind]||spriteRects.supplies;return '<svg aria-hidden="true" viewBox="'+box.join(' ')+'" width="100%" height="100%" style="display:block;overflow:hidden"><image href="transition-life/assets/'+(essential?'essentials-atlas.png':'furniture-atlas.png')+'" width="1448" height="1086"/></svg>';}
function furnitureWidth(p){return ['bed','frame','couch','table','dining','rug'].includes(p.kind)?25:['dresser','chair','vacuum'].includes(p.kind)?20:['tv','lamp','console','art','mirror'].includes(p.kind)?16:11;}
function avatar(r,l){const a=r.avatar||{};const color=(value,fallback)=>/^#[a-f\d]{3,8}$/i.test(value||'')?value:fallback;return '<div class="resident-avatar" id="residentAvatar" style="left:'+l.avatar.x+'%;top:'+l.avatar.y+'%;z-index:'+Math.round(l.avatar.y)+'"><svg viewBox="0 0 70 165" aria-label="Your character"><defs><linearGradient id="shirtShade"><stop stop-color="'+color(a.shirt,'#258b86')+'"/><stop offset="1" stop-color="#184c53"/></linearGradient></defs><ellipse cx="35" cy="156" rx="26" ry="5" fill="#0003"/><path d="M20 104 L18 145 Q24 151 31 145 L36 115 L39 147 Q49 151 54 144 L50 104" fill="'+color(a.pants,'#344458')+'"/><path d="M17 144 Q8 151 14 156 L29 156 L30 145 M41 145 L40 156 L60 156 Q62 150 53 145" fill="#293036"/><path d="M17 60 Q2 68 6 98 Q8 104 14 99 L20 76 M51 60 Q66 68 63 98 Q61 105 55 99 L49 76" fill="'+color(a.skin,'#b77c55')+'"/><path d="M18 58 Q35 48 51 58 L56 108 Q36 119 15 107 Z" fill="url(#shirtShade)"/><rect x="28" y="45" width="14" height="18" rx="7" fill="'+color(a.skin,'#b77c55')+'"/><ellipse cx="35" cy="29" rx="22" ry="27" fill="'+color(a.skin,'#b77c55')+'"/><path d="M13 30 Q6 -2 35 0 Q64 -2 57 31 L52 17 Q36 27 18 15Z" fill="'+color(a.hair,'#382a25')+'"/><ellipse cx="26" cy="30" rx="2" ry="3" fill="#30271e"/><ellipse cx="44" cy="30" rx="2" ry="3" fill="#30271e"/><path d="M28 41 Q35 46 42 41" fill="none" stroke="#713e31" stroke-width="2"/></svg></div>';}
function roomHot(label,act,x,y,id=''){return '<button class="hotspot" style="left:'+x+'%;top:'+y+'%" data-act="'+act+'" data-id="'+id+'" data-x="'+x+'" data-y="'+Math.max(60,y)+'">'+label+'</button>';}
function renderHome(){const {w,r,l}=state();if(!l.housing){shell('<section class="panel"><h1>Your life in Transition Town starts with a home.</h1><p>Choose housing, complete the existing application, then pay your move-in costs from your checking account.</p><div class="row">'+link('Explore existing housing','transition-town.html?life=housing','primary')+link('Browse houses','housing-office.html')+btn('My housing applications','housing')+'</div><div class="warning" style="margin-top:20px">Your checking balance is '+cash(r.checking)+'. No extra starting money is added for Transition Life.</div></section>');if(new URLSearchParams(location.search).get('housing'))housing();return;}
 room=l.room||room;const fixture=room==='kitchen'?roomHot('Refrigerator','fridge',24,51)+roomHot('Stove / oven','stove',66,49)+roomHot('Sink','home-action',46,48,'sink')+roomHot('Clean kitchen','home-action',83,76,'clean'):room==='bathroom'?roomHot('Shower','home-action',80,43,'shower')+roomHot('Take bath','home-action',66,64,'bath')+roomHot('Sink','home-action',20,53,'sink')+roomHot('Toilet','toilet',38,61):room==='bedroom'?roomHot(K.placed(r,'mattress')?'Bed':'Sleep on floor','sleep',50,70):roomHot('Relax','home-action',31,69,'relax')+roomHot('Leave home','leave',83,55);
 const furnishing=l.inventory.filter(i=>i.placement?.room===room&&!i.returned&&!i.deliveryPending).map(i=>'<button class="furniture" data-act="furniture" data-id="'+esc(i.uid)+'" style="left:'+i.placement.x+'%;top:'+i.placement.y+'%;width:'+furnitureWidth(i)+'%;z-index:'+Math.round(i.placement.y)+'" aria-label="'+esc(i.name)+'">'+art(i)+'<span class="label">'+esc(i.name)+'</span></button>').join('');
 shell('<section class="scene-wrap" aria-label="Playable '+room+'"><img class="scene-image" src="transition-life/assets/home-'+room+'.webp" alt="Your '+room+' with permanent fixtures and open space"><div id="homeStage" class="home-stage'+(placing?' placing':'')+'">'+(!r.utilities.electricOn?'<div class="night-overlay"></div>':'')+'<div class="scene-heading"><h1>'+({living:'Living room',bedroom:'Bedroom',kitchen:'Kitchen',bathroom:'Bathroom'}[room])+'</h1><p>'+esc(l.housing.name)+'</p></div>'+furnishing+avatar(r,l)+fixture+'<div class="stage-footer">'+(placing?'Tap the floor where you want your item.':'Tap the floor to walk. Tap an object to use it. Buy and place furniture to make this home yours.')+'</div></div></section><nav class="room-tabs" aria-label="Rooms">'+['living','kitchen','bedroom','bathroom'].map(x=>btn({living:'Living room',kitchen:'Kitchen',bedroom:'Bedroom',bathroom:'Bathroom'}[x],'room',x,x===room?'primary':'')).join('')+btn(placing?'Cancel placement':'Place / rearrange','place-menu','', 'gold')+'</nav><section class="panel compact"><div class="row spread"><span>Electricity: <b>'+(r.utilities.electricOn?'ON':'OFF')+'</b> · Water: <b>'+(r.utilities.waterOn?'ON':'OFF')+'</b> · Internet: <b>'+(r.utilities.internetOn?'ON':'Optional — not connected')+'</b></span>'+btn('Set up / manage utilities','bills')+'</div></section>');
 const stage=document.getElementById('homeStage');stage.addEventListener('click',e=>{if(e.target.closest('button'))return;let box=stage.getBoundingClientRect(),x=(e.clientX-box.left)/box.width*100,y=(e.clientY-box.top)/box.height*100;if(placing){if(y<53)return toast('Choose an open spot on the floor.');change(r=>K.place(r,placing,room,x,y));placing=null;renderHome();toast('Placed! Tap your furniture to use or rearrange it.');}else walk(x,Math.max(58,Math.min(84,y)));});
 if(l.keysPending)keys();else if(!l.introSeen){change(r=>r.life.introSeen=true);guide();}
}
function walk(x,y){change(r=>r.life.avatar={x:Math.max(10,Math.min(90,x)),y:Math.max(57,Math.min(86,y))});let a=document.getElementById('residentAvatar');if(a){a.style.left=x+'%';a.style.top=y+'%';a.classList.add('walking');setTimeout(()=>a.classList.remove('walking'),800);}}
function keys(){modal('You got the keys!','<div class="keys"><div class="key-art" aria-hidden="true">⚿</div><h2>YOU GOT THE KEYS!</h2><p>'+esc(state().l.housing.name)+'</p><p>Your home has its permanent fixtures. The refrigerator and rooms are ready for you to stock and furnish.</p>'+btn('ENTER MY NEW HOME','enter-new','','primary')+'</div>');}
function guide(){const {r}=state(),all=C.guide.flatMap(g=>g.items),owned=all.filter(([tag])=>K.has(r,tag)).length;modal('My First Home • Move-In Guide','<p>Start with what you need. Functional basic items count just as much as premium ones.</p><strong>'+owned+' of '+all.length+' ready or ordered</strong><div class="progress"><i style="width:'+owned/all.length*100+'%"></i></div><div class="grid single-mobile">'+C.guide.map(g=>'<section class="card"><h3>'+g.title+'</h3><ul class="checklist">'+g.items.map(([tag,label])=>'<li><span class="check '+(K.has(r,tag)?'owned':'')+'">'+(K.has(r,tag)?'✓':'')+'</span><span>'+label+'</span></li>').join('')+'</ul></section>').join('')+'</div><p class="small">Updates automatically from your personal purchases. Large items can be owned while delivery is pending. Food reflects the supply you still have.</p><div class="row">'+link('Shop Home & Beyond','home-beyond.html','primary')+link('Get groceries','grocery-store.html')+btn('Utilities next','bills')+'</div>');}
function inventory(){const {l}=state();modal('My household inventory','<div class="row">'+btn('Furniture deliveries','deliveries','','primary')+btn('Move-in guide','guide')+'</div>'+['bedroom','kitchen','bathroom','living','any'].map(room=>{let items=l.inventory.filter(i=>!i.returned&&i.qty>0&&i.room===room);return items.length?'<h3 style="margin-top:25px">'+esc(room==='any'?'Household supplies':room)+'</h3>'+items.map(i=>'<div class="receipt-line"><span><b>'+esc(i.name)+'</b> × '+i.qty+'<small>'+(i.deliveryPending?'Awaiting scheduled delivery':i.placement?'Placed in '+i.placement.room:'Ready to place / use')+'</small></span>'+(!i.deliveryPending?btn(i.placement?'Rearrange':'Place','place',i.uid):'')+'</div>').join(''):'';}).join('')+'<h3 style="margin-top:25px">Food</h3>'+l.food.filter(f=>f.qty>0).map(f=>'<p>'+esc(f.name)+' · '+f.qty+' portions</p>').join('')+(!l.food.some(f=>f.qty>0)?'<p>Your refrigerator is empty.</p>':'')+'<p class="small">Small supplies are available from your cupboards even when not displayed. Furniture must be placed before use.</p>');}
function deliveries(){const {l}=state();modal('Furniture deliveries',l.orders.filter(o=>o.items.some(x=>C.product(x.id)?.large)).map(o=>'<section class="card" style="margin:12px 0"><h3>Order '+esc(o.id)+'</h3><p>'+o.items.map(x=>esc(C.product(x.id)?.name)+' × '+x.qty).join(', ')+'</p>'+(o.delivery?'<p>'+esc(o.delivery.date)+' · '+esc(o.delivery.window)+' · '+esc(o.delivery.status)+'</p>'+(o.delivery.status!=='Delivered'&&K.diffDays(l.date,o.delivery.date)>=0?btn('Answer door & receive delivery','receive',o.id,'primary'):''):'<p>Large items are waiting in the warehouse. Schedule free standard delivery to your home.</p>'+btn('Schedule delivery','schedule',o.id,'primary'))+'</section>').join('')||'<p>No furniture deliveries yet.</p>');}
function schedule(id){const {l}=state();modal('Schedule furniture delivery','<p>Standard delivery is free. Delivery is available on the next simulation day or later. Sleeping for the night moves to the next day.</p><label>Delivery date<input id="deliveryDate" type="date" min="'+K.plusDays(l.date,1)+'" max="'+K.plusDays(l.date,30)+'" value="'+K.plusDays(l.date,1)+'"></label><label>Arrival window<select id="deliveryWindow"><option>Morning</option><option>Afternoon</option></select></label>'+btn('Confirm delivery','schedule-confirm',id,'primary'));}
function placeMenu(){if(placing){placing=null;return render();}inventory();}
function startPlace(id){const {l}=state(),i=l.inventory.find(x=>x.uid===id);if(!l.housing)return toast('Obtain housing first.');room=i.room==='any'?l.room:i.room;change(r=>r.life.room=room);placing=id;close();if(isStore){sessionStorage.ttLifePlace=id;location.href='transition-life.html';}else renderHome();}
function furniture(id){const {l}=state(),i=l.inventory.find(x=>x.uid===id);if(!i)return;modal(i.name,'<div class="row">'+(i.tags.includes('mattress')?btn('Sleep options','sleep','','primary'):'')+(i.tags.includes('tv')?btn('Watch television','home-action','tv','primary'):'')+(i.tags.includes('games')?btn('Play offline game','home-action','games','primary'):'')+(i.tags.includes('seating')?btn('Relax','home-action','relax','primary'):'')+(i.tags.includes('table')?btn('Eat a prepared meal','fridge','','primary'):'')+btn('Rearrange','place',id)+btn('Put away','unplace',id)+'</div>');}
function sleep(){const {r}=state(),bed=K.placed(r,'mattress');modal('Rest at home',bed?'<p>Your mattress is ready. Choose how long to rest.</p><div class="row">'+btn('Nap','home-action','nap')+btn('Go to bed','home-action','bed')+btn('Sleep for the night','home-action','night','primary')+'</div>':'<p>You don’t own a placed mattress yet. Floor sleeping is temporary and restores much less energy (up to 65%).</p><div class="row">'+btn('Sleep on floor','home-action','floor')+btn('Sleep on floor for the night','home-action','floor-night','primary')+link('Shop mattresses','home-beyond.html?dept=bedroom')+'</div>');}
function homeAction(kind){const {r,l}=state();const test=K.clone(r);K.action(test,kind);
 const labels={shower:'Taking a shower',bath:'Taking a bath',sink:'Washing hands',relax:'Taking a quiet break',tv:'Watching television',games:'Catch the stars',floor:'Resting on the floor','floor-night':'Sleeping on the floor',nap:'Taking a nap',bed:'Going to bed',night:'Sleeping for the night',clean:'Cleaning your home'};
 const sleeping=['floor','floor-night','nap','bed','night'].includes(kind),water=['shower','bath','sink'].includes(kind),scene=sleeping?'bedroom':water?'bathroom':kind==='clean'?'kitchen':'living';
 const copy=K.clone(l);copy.avatar={x:water?78:52,y:water?72:80};
 const furnishings=l.inventory.filter(i=>i.placement?.room===scene&&!i.returned&&!i.deliveryPending).map(i=>'<div class="activity-furniture" style="left:'+i.placement.x+'%;top:'+i.placement.y+'%;width:'+furnitureWidth(i)+'%">'+art(i)+'</div>').join('');
 let overlay=water?'<div class="water-stream"></div><div class="soap-bubbles"><i></i><i></i><i></i></div>':sleeping?'<div class="sleep-cloud">Z z z</div>':kind==='tv'?'<div class="tv-picture"><span>TRANSITION WILDLIFE</span><i>🌳 🦋 🌿</i></div>':kind==='clean'?'<div class="clean-spots"><i>✧</i><i>✧</i><i>✧</i></div>':'';
 modal(labels[kind]||'At home','<div class="activity-scene '+(sleeping?'activity-sleep ':'')+(water?'activity-water ':'')+(kind==='clean'?'activity-clean':'')+'"><img src="transition-life/assets/home-'+scene+'.webp" alt="Your character at home">'+furnishings+avatar(r,copy)+overlay+(kind==='games'?'<div class="game-screen"><p id="starScore">Catch 6 stars · 0 / 6</p><button id="catchStar" aria-label="Catch the star">★</button></div>':'')+'</div><p id="actionCaption">'+(kind==='games'?'Tap the moving star. Your own gaming system works offline.':labels[kind]+'.')+'</p>'+(kind==='games'?'':'<div class="action-progress running"><i></i></div>')+'<p class="small">'+(kind==='night'||kind==='floor-night'?'One simulation day passes. Bills and scheduled deliveries move forward.':'Your needs change when the activity finishes.')+'</p>');
 function finish(){try{change(r=>K.action(r,kind));close();render();toast('Finished. Your needs and home are saved.');}catch(e){toast(e.message);}}
 if(kind==='games'){let caught=0;document.getElementById('catchStar').onclick=e=>{caught++;if(caught===6)return finish();document.getElementById('starScore').textContent='Catch 6 stars · '+caught+' / 6';e.currentTarget.style.left=(15+Math.random()*67)+'%';e.currentTarget.style.top=(35+Math.random()*40)+'%';};return;}
 let elapsed=0,last=performance.now();actionTimer=setInterval(()=>{const now=performance.now();if(!document.hidden)elapsed+=now-last;last=now;if(elapsed>=4000){clearInterval(actionTimer);actionTimer=null;finish();}},100);
}
function fridge(){const {r,l}=state();const food=l.food.filter(f=>f.qty>0),meals=l.meals;modal('My refrigerator & pantry',(!r.utilities.electricOn?'<p class="warning">The refrigerator has no electricity. Connect power for refrigerated food. Pantry foods are still available.</p>':'')+(!food.length&&!meals.length?'<h3>Your refrigerator is empty.</h3><p>Bring groceries home from the existing Grocery Store.</p>':'')+food.map(f=>'<div class="receipt-line"><span>'+esc(f.name)+'<small>'+f.qty+' portions'+(f.raw?' · must be cooked':'')+'</small></span>'+(['fruit','bread','snack','ready','cereal','milk'].includes(f.tag)&&!f.raw?btn('Eat','eat',f.id):'<span class="tag">Cook first</span>')+'</div>').join('')+meals.map(m=>'<div class="receipt-line"><span>'+esc(m.name)+'<small>Prepared meal</small></span>'+btn('Eat meal','eat-meal',m.id,'primary')+'</div>').join('')+'<div class="row" style="margin-top:20px">'+link('Go grocery shopping','grocery-store.html','primary')+btn('Use stove','stove')+btn('Eat out','eat-out')+link('Check my money','transition-town.html?life=bank')+'</div>');}
function stove(){const {r,l}=state();modal('What can I cook?','<p>Recipes use the groceries and cookware you actually own.</p><div class="grid single-mobile">'+C.recipes.map(recipe=>'<article class="card"><h3>'+recipe.name+'</h3><p>'+Object.entries(recipe.ingredients).map(([t,n])=>n+' portion '+t).join(' + ')+'</p><p class="small">Need: '+recipe.tools.join(', ')+'</p>'+(K.recipeAvailable(r,recipe.id)?btn('Prepare this meal','cook-start',recipe.id,'primary'):'<span class="tag">Missing ingredients or cookware</span>')+'</article>').join('')+'</div>');}
function cookStart(id){const {r}=state();const test=K.clone(r);K.cook(test,id);const recipe=C.recipes.find(x=>x.id===id);cookTask={id,step:0,stir:0};cookStep();}
function cookStep(){const recipe=C.recipes.find(x=>x.id===cookTask.id);body.innerHTML='<h2 id="dialogTitle">Cooking '+esc(recipe.name)+'</h2><div class="progress"><i style="width:'+cookTask.step/recipe.steps.length*100+'%"></i></div><p>Step '+(cookTask.step+1)+' of '+recipe.steps.length+'</p><h3>'+esc(recipe.steps[cookTask.step])+'</h3>'+(cookTask.step===2?'<div id="cookZone" class="cook-zone"><div class="pan-food" id="panFood"></div></div><p id="stirStatus">Stir progress: 0 / 12</p>':'<div class="task-ticket">Use the action below to carry out this step.</div>')+btn(recipe.steps[cookTask.step],'cook-next','','primary');if(cookTask.step===2){let held=false,last=null,zone=document.getElementById('cookZone');zone.onpointerdown=e=>{held=true;last={x:e.clientX,y:e.clientY};zone.setPointerCapture(e.pointerId);};zone.onpointermove=e=>{if(!held)return;if(Math.hypot(e.clientX-last.x,e.clientY-last.y)>12){last={x:e.clientX,y:e.clientY};cookTask.stir=Math.min(12,cookTask.stir+1);document.getElementById('stirStatus').textContent='Stir progress: '+cookTask.stir+' / 12';document.getElementById('panFood').style.transform='rotate('+cookTask.stir*30+'deg) translateX(5px)';}};zone.onpointerup=zone.onpointercancel=()=>held=false;body.insertAdjacentHTML('beforeend',btn('Stir once (keyboard / tap)','stir'));}}
function bills(){change(r=>K.processBills(r));const {r,l}=state();if(!l.housing)return modal('Bills & utilities','<p>Obtain housing first. Utilities are set up after you get the keys.</p>'+link('Housing choices','transition-town.html?life=housing','primary'));modal('Household bills & utilities','<p>'+esc(l.date)+' · Simulation time advances when you sleep for the night. These are classroom scenarios, not real legal deadlines.</p><h3>Utility connections</h3><div class="grid">'+Object.entries(K.utilSpecs).filter(([k])=>k!=='gas'||l.housing.gas).map(([k,s])=>'<div class="card"><h3>'+s.name+(k==='internet'?' · optional':'')+'</h3><p>'+(r.utilities[k+'On']?'Active':r.utilities[k+'Deposit']?'Disconnected':'Not connected')+' · '+cash(s.monthly)+'/month</p>'+(!r.utilities[k+'On']?btn(r.utilities[k+'Deposit']?'Reconnect • $25':'Set up • '+cash(s.deposit),'utility',k,'primary'):'<span class="tag">Service ON</span>')+'</div>').join('')+'</div><h3 style="margin-top:24px">My bills</h3>'+l.bills.slice().sort((a,b)=>a.due.localeCompare(b.due)).map(b=>'<div class="card" style="margin:10px 0"><div class="row spread"><div><b>'+esc(K.utilSpecs[b.kind]?.name||b.kind.toUpperCase())+'</b><p>'+cash(b.paid?(b.totalPaid??b.amount):K.billTotal(b,l))+' · Due '+b.due+'</p></div><span class="tag bill-state '+(K.diffDays(l.date,b.due)>0&&!b.paid?'danger':'')+'">'+K.stage(b,l)+'</span></div>'+(!b.paid?'<div class="row">'+btn('Pay balance','pay-bill',b.id,'primary')+btn('AutoPay: '+(b.autopay?'ON':'OFF'),'autopay',b.id)+'</div>':'<p class="small">Paid '+b.paidOn+'</p>')+'</div>').join('')+'<p class="small">AutoPay starts OFF. Late fees: rent $25; other bills $15 after 7 simulation days. Utility reconnection is $25 after overdue balances are cleared. A risk notice never automatically removes a student’s home.</p><div class="row">'+btn('Use savings','savings')+btn('Adjust budget','budget')+btn('Contact landlord / lender','help','Housing payment plan')+link('Housing assistance','transition-town.html?life=assistance')+btn('Ask Miss Kayla for help','help','Housing help')+'</div>');}
function housing(){const {w,l}=state();const apps=(w.housingApplications||[]).map((a,i)=>({...a,index:i})).filter(a=>(a.student||a.resident||a.name)===captured);modal('My housing applications',apps.length?apps.map(a=>'<section class="card" style="margin:12px 0"><h3>'+esc(a.property)+' '+esc(a.unit||'')+'</h3><p>Status: '+esc(a.status)+'</p>'+(a.tenure==='owner'?'<p>Offer '+cash(a.price)+' · down payment '+cash(a.down)+'<br>Financing: '+esc(a.financing)+'</p>':'<p>Rent '+cash(a.rent)+' / month · deposit '+cash(a.deposit??a.rent)+'<br>Total move-in: '+cash(Number(a.rent)+Number(a.deposit??a.rent))+'</p>')+(a.status==='Approved'&&!l.housing?btn('Review & accept housing','housing-review',a.index,'primary'):'')+'</section>').join(''):'<p>No applications yet.</p>'+link('Compare existing housing','transition-town.html?life=housing','primary'));}
function housingReview(index){const {w}=state(),a=w.housingApplications[index],owner=a.tenure==='owner';const amount=owner?(a.financing==='Cash purchase'?a.price:a.down):Number(a.rent)+Number(a.deposit??a.rent);const principal=owner&&a.financing!=='Cash purchase'?a.price-a.down:0,rate=.06/12,monthly=owner?(principal?K.money(principal*rate/(1-(1+rate)**-360)):0):a.rent;modal('Review your housing agreement','<h3>'+esc(a.property)+'</h3><p><b>Due today: '+cash(amount)+'</b></p><p>Monthly '+(owner?'mortgage':'rent')+': '+cash(monthly)+'</p>'+(principal?'<p>Simulated fixed mortgage: 6% interest for 30 years. Principal '+cash(principal)+'.</p>':'')+'<p>Utilities, furniture, food and household supplies are separate. Your home starts mostly empty.</p><label><input type="checkbox" id="housingAgree"> I reviewed the cost and want to use my Transition Town checking account.</label>'+btn('Pay & get my keys','acquire',index,'primary'));}
function renderStore(){const {l}=state();let scene=shopScene,department=C.departments.find(x=>x[0]===scene);if(scene==='exterior'){shell('<section class="scene-wrap store-stage"><img class="scene-image" src="transition-life/assets/store-exterior.webp" alt="Transition Town Home & Beyond storefront, Now Hiring"><button class="hotspot shop-door" data-act="shop-scene" data-id="entrance">Enter Home & Beyond</button><button class="hotspot shop-hiring" data-act="jobs">NOW HIRING • Apply</button></section><section class="panel compact"><div class="row spread"><span>Your first home starts with the essentials.</span>'+btn('My cart ('+l.cart.reduce((s,x)=>s+x.qty,0)+')','cart','','primary')+'</div></section>');return;}
 let content='<section class="scene-wrap store-stage"><img class="scene-image" src="transition-life/assets/store-'+scene+'.webp" alt="Home & Beyond '+esc(department?.[1]||scene)+'"><div class="scene-heading"><h1>'+esc(department?.[1]||({entrance:'Welcome home.',checkout:'Checkout',service:'Customer service',employee:'Employee entrance'}[scene]))+'</h1></div>'+(scene==='entrance'?roomHot('Departments','department-menu',49,69)+roomHot('Customer Service','shop-scene',22,48,'service')+roomHot('Checkout','shop-scene',82,54,'checkout')+roomHot('Employee Entrance','shop-scene',67,38,'employee'):'')+'</section><nav class="room-tabs">'+btn('Store entrance','shop-scene','entrance')+btn('Departments','department-menu')+btn('Cart ('+l.cart.reduce((s,x)=>s+x.qty,0)+')','cart','','primary')+btn('Customer service','shop-scene','service')+btn('Employee entrance','shop-scene','employee')+'</nav>';
 if(department)content+='<section class="panel"><div class="row spread"><p>Compare what works for your home and budget.</p>'+btn('Compare selected ('+compare.length+')','compare')+'</div><div class="grid">'+C.products.filter(p=>p.dept===scene).map(p=>'<article class="card '+(compare.includes(p.id)?'compare':'')+'"><div class="product-photo">'+art(p)+'</div><span class="tag">'+p.tier+'</span><h3>'+p.name+'</h3><div class="price">'+cash(p.price)+'</div><p class="small">'+(p.large?'Large item · schedule delivery':'Take home after checkout')+'</p><div class="row">'+btn('Add to cart','add-cart',p.id,'primary')+btn(compare.includes(p.id)?'Selected':'Compare','toggle-compare',p.id)+'</div></article>').join('')+'</div></section>';
 if(scene==='checkout')content+='<section class="panel"><h2>Choose your register</h2><p>Review the cart, place every item on the register, then authorize the payment from checking.</p><div class="row">'+btn('Register 1 · Open','checkout-start','','primary')+btn('Register 2 · Open','checkout-start')+btn('Register 3 · Open','checkout-start')+'</div></section>';
 if(scene==='service')content+='<section class="panel"><h2>How can we help?</h2><div class="row">'+btn('Returns & exchanges','returns','','primary')+btn('Order pickup / delivery','deliveries')+btn('Complaint or compliment','feedback')+'</div></section>';
 if(scene==='employee')content+='<section class="panel"><h2>Employee center</h2><div class="row">'+btn('Time clock & job assignments','employee','','primary')+btn('Open positions / apply','jobs')+btn('My application status','applications')+'</div><p class="small">Training is hands-on. Pay requires a hired role, completed training, five active real minutes, and verified work tasks.</p></section>';
 shell(content);
}
function departments(){modal('Where would you like to shop?','<div class="grid">'+C.departments.map(([id,label])=>'<button class="department-card" data-act="shop-scene" data-id="'+id+'"><img src="transition-life/assets/store-'+id+'.webp" alt="'+label+'" loading="lazy"><span>'+label+'</span></button>').join('')+'</div>');}
function cart(){const {l}=state(),total=l.cart.reduce((s,x)=>s+C.product(x.id).price*x.qty,0);modal('My shopping cart',l.cart.length?l.cart.map(x=>'<div class="receipt-line"><span><b>'+C.product(x.id).name+'</b><small>'+cash(C.product(x.id).price)+' each · '+x.qty+'</small></span><div class="row">'+btn('−','cart-minus',x.id)+btn('+','add-cart',x.id)+'</div></div>').join('')+'<div class="receipt-line total"><span>Total</span>'+cash(total)+'</div><p>All prices are simulated. No extra tax or delivery charge.</p><div class="row">'+btn('Go to checkout','shop-scene','checkout','primary')+btn('Keep shopping','department-menu')+'</div>':'<p>Your cart is empty. Choose a department to start.</p>'+btn('Departments','department-menu','','primary'));}
let scanItems=[],scanCount=0;
function checkoutStart(){const {l}=state();scanItems=l.cart.flatMap(x=>Array.from({length:x.qty},()=>x.id));scanCount=0;if(!scanItems.length)return cart();drawCheckout();}
function drawCheckout(){const total=scanItems.reduce((s,id)=>s+C.product(id).price,0);modal('Home & Beyond register','<p>Tap each item to scan it.</p><div class="scan-belt">'+scanItems.map((id,i)=>'<button class="'+(i<scanCount?'scanned':'')+'" data-act="scan-shop" data-id="'+i+'" '+(i!==scanCount?'disabled':'')+'>'+'<span class=work-product>'+art(C.product(id))+'</span>'+C.product(id).name+'<br>'+cash(C.product(id).price)+'</button>').join('')+'</div><p>'+scanCount+' / '+scanItems.length+' scanned</p><div class="receipt-line total"><span>Total</span>'+cash(total)+'</div>'+(scanCount===scanItems.length?btn('Pay '+cash(total)+' from checking','pay-shop','','primary'):'')+'<p class="small">Your bank is charged once after you confirm payment.</p>');}
function returns(){const {l}=state();modal('Returns & exchanges','<p>Unused, unplaced purchases can be returned within 30 simulation days. For an exchange, return the eligible item and select a replacement; the price difference stays in your checking account.</p>'+l.inventory.filter(i=>!i.returned&&l.orders.some(o=>o.id===i.orderId)).map(i=>'<div class="receipt-line"><span>'+esc(i.name)+' × '+i.qty+'<small>'+(i.used?'Used — not returnable':i.placement?'Put away before requesting a return':'Receipt available')+'</small></span>'+(!i.used&&!i.placement?btn('Return • '+cash(i.price*i.qty),'return-item',i.uid):'')+'</div>').join(''));}
function teacher(){if(!S.teacher(captured))throw Error('Open Miss Kayla’s profile first.');const {w}=state();modal('Miss Kayla • Transition Life','<p>Overview of residents saved on this device. Life alerts also go through the existing Central Hub notification system when online.</p><div class="row">'+btn(S.sandbox()?'Exit test mode':'Start safe test mode',S.sandbox()?'test-exit':'test-start','','gold')+link('Cross-device alerts','miss-kayla-inbox.html?category=alert')+btn('Housing approvals','teacher-housing')+link('Job applications','transition-town.html?life=job-review')+'</div>'+(S.sandbox()?'<p class="warning">Practice copy only. Advance days to test overdue bills without affecting student progress.</p><div class="row">'+btn('Advance 7 days','test-days',7)+btn('Advance 30 days','test-days',30)+btn('Practice move-in','test-home')+'</div>':'')+'<div class="grid single-mobile" style="margin-top:20px">'+Object.entries(w.residents).filter(([n])=>!S.teacher(n)).map(([n,r])=>{const copy=K.clone(r),a=K.alerts(copy);return '<article class="card"><h3>'+esc(n)+'</h3><p>'+esc(r.home||'Housing not selected')+'</p>'+a.map(x=>'<div class="tag '+(/risk|disconnected|past due/i.test(x)?'danger':'')+'">'+esc(x)+'</div>').join('')+'<p>Checking '+cash(r.checking)+'</p></article>';}).join('')+'</div>');}
function teacherHousing(){if(!S.teacher(captured))throw Error('Teacher view required.');const {w}=state();modal('Housing reviews on this device',(w.housingApplications||[]).map((a,i)=>'<section class="card" style="margin:12px 0"><h3>'+esc(a.student||a.resident||a.name)+' · '+esc(a.property)+'</h3><p>'+esc(a.unit||'')+' · '+esc(a.status)+'</p><p>'+(a.tenure==='owner'?'Price '+cash(a.price)+' · down '+cash(a.down)+' · '+esc(a.financing):'Rent '+cash(a.rent)+' · deposit '+cash(a.deposit??a.rent))+'</p>'+(!a.closed?'<div class="row">'+btn('Approve terms','housing-approve',i,'primary')+btn('Request changes','housing-changes',i)+'</div>':'')+'</section>').join('')||'<p>No housing applications on this device yet.</p>');}
function help(topic){modal(topic,'<p>Write a short simulated request. It will be saved for Miss Kayla’s existing Central Hub.</p><label>Your request<textarea id="helpText" rows="4" maxlength="1200" placeholder="Explain what you need and suggest a plan."></textarea></label>'+btn('Send request','help-send',topic,'primary'));}
const handlers={
 'guide':guide,'inventory':inventory,'deliveries':deliveries,'schedule':schedule,'bills':bills,'teacher':teacher,'teacher-housing':teacherHousing,'housing':housing,'housing-review':housingReview,'place-menu':placeMenu,'place':startPlace,'fridge':fridge,'stove':stove,'sleep':sleep,'furniture':furniture,'home-action':homeAction,'cook-start':cookStart,'cart':cart,'department-menu':departments,'checkout-start':checkoutStart,'returns':returns,'help':help,
 'room':id=>{placing=null;change(r=>r.life.room=id);renderHome();},
 'enter-new':()=>{change(r=>{r.life.keysPending=false;r.life.introSeen=true;});close();render();guide();},
 'leave':()=>modal('Head out into Transition Town','<div class="grid">'+link('Grocery shopping','grocery-store.html','primary')+link('Home & Beyond','home-beyond.html')+link('Go to work','transition-town.html?life=jobs')+link('Transition Park','transition-town.html?life=park')+link('Pizza shop','pizza-shop.html')+link('Town map','transition-town.html')+'</div>'),
 'eat-out':()=>modal('Eat out in Transition Town','<p>Choose a restaurant. Purchases use the same checking balance.</p><div class="row">'+link('Pizza shop','pizza-shop.html','primary')+link('Coffee shop','coffee-shop.html')+'</div>'),
 'toilet':()=>{const {r}=state();if(!r.utilities.waterOn)throw Error('The toilet needs active water service.');toast(K.has(r,'toilet-paper',true)?'The bathroom is stocked and ready.':'Remember to buy toilet paper for your bathroom.');},
 'unplace':id=>{change(r=>r.life.inventory.find(i=>i.uid===id).placement=null);close();render();},
 'receive':id=>{change(r=>K.receive(r,id));deliveries();toast('Delivery received. Place your furniture from inventory.');},
 'schedule-confirm':id=>{change(r=>K.schedule(r,id,document.getElementById('deliveryDate').value,document.getElementById('deliveryWindow').value));deliveries();},
 'eat':id=>{change(r=>{const f=r.life.food.find(x=>x.id===id);if(['milk','ready'].includes(f?.tag)&&!r.utilities.electricOn)throw Error('Connect refrigerator power for refrigerated foods. Pantry foods are available.');K.eat(r,id);});fridge();},'eat-meal':id=>{change(r=>K.eat(r,id,true));fridge();},
 'stir':()=>{if(cookTask){cookTask.stir=Math.min(12,cookTask.stir+1);document.getElementById('stirStatus').textContent='Stir progress: '+cookTask.stir+' / 12';}},
 'cook-next':()=>{if(!cookTask)return;if(cookTask.step===2&&cookTask.stir<12)return toast('Stir the food first. Drag in the pan or tap Stir once.');cookTask.step++;if(cookTask.step>=C.recipes.find(x=>x.id===cookTask.id).steps.length){change(r=>K.cook(r,cookTask.id));cookTask=null;fridge();toast('Meal prepared! Ingredients were used from your food supply.');}else cookStep();},
 'utility':id=>{change(r=>K.utility(r,id));bills();if(!isStore)renderHome();},'pay-bill':id=>{change(r=>K.payBill(r,id));bills();},
 'autopay':id=>{change(r=>{let b=r.life.bills.find(x=>x.id===id);const enabled=!b.autopay;r.life.bills.filter(x=>x.kind===b.kind&&!x.paid).forEach(x=>x.autopay=enabled);});bills();},
 'savings':()=>modal('Move savings to checking','<p>Savings available: '+cash(state().r.savings)+'</p><label>Transfer amount<input id="savingsAmount" type="number" min="0.01" step="0.01" inputmode="decimal"></label>'+btn('Transfer','savings-transfer','','primary')),
 'savings-transfer':()=>{change(r=>{let a=K.money(document.getElementById('savingsAmount').value);if(!Number.isFinite(a)||a<=0||a>Number(r.savings||0))throw Error('Choose an amount available in savings.');r.savings=K.money(r.savings-a);r.checking=K.money(Number(r.checking)+a);K.log(r,0,'Transferred savings to checking: '+cash(a));});bills();},
 'budget':()=>{const {l}=state();modal('My household budget','<p>Monthly housing: '+cash(l.housing?.monthly)+'</p><p>Active monthly utilities: '+cash(Object.entries(K.utilSpecs).filter(([k])=>state().r.utilities[k+'On']).reduce((s,[k,u])=>s+u.monthly,0))+'</p><label>Food budget<input id="foodBudget" type="number" min="0" value="'+(l.budget?.food||150)+'"></label><label>Home supplies budget<input id="supplyBudget" type="number" min="0" value="'+(l.budget?.supplies||50)+'"></label>'+btn('Save my plan','save-budget','','primary'));},
 'save-budget':()=>{change(r=>{const food=Number(document.getElementById('foodBudget').value),supplies=Number(document.getElementById('supplyBudget').value);if(!Number.isFinite(food)||!Number.isFinite(supplies)||food<0||supplies<0)throw Error('Use amounts of zero or more.');r.life.budget={food,supplies};});bills();},
 'help-send':topic=>{const text=document.getElementById('helpText').value.trim();if(!text)throw Error('Write your request first.');change((r,w)=>{w.cityHallInbox=w.cityHallInbox||[];w.cityHallInbox.push({id:K.uid(),from:captured,department:'Transition Life / Housing',type:topic,text,date:new Date().toISOString()});});close();toast('Your request was saved for Miss Kayla.');},
 'housing-approve':i=>{if(!S.teacher(captured))throw Error('Teacher view required.');change((r,w)=>w.housingApplications[i].status='Approved');teacherHousing();},'housing-changes':i=>{if(!S.teacher(captured))throw Error('Teacher view required.');change((r,w)=>w.housingApplications[i].status='Changes requested');teacherHousing();},
 'acquire':i=>{if(!document.getElementById('housingAgree').checked)throw Error('Review and accept the housing agreement first.');change((r,w)=>{const a=w.housingApplications[i];if((a.student||a.resident||a.name)!==captured)throw Error('This application belongs to another resident.');K.acquire(r,a);});close();renderHome();},
 'shop-scene':id=>{if(!isStore){location.href='home-beyond.html?dept='+encodeURIComponent(id);return;}shopScene=id;close();renderStore();window.scrollTo({top:0,behavior:'smooth'});},
 'add-cart':id=>{change(r=>{if(!C.product(id))throw Error('Unknown product.');let c=r.life.cart.find(x=>x.id===id);if(c){if(c.qty>=99)throw Error('Cart limit reached for this item.');c.qty++;}else r.life.cart.push({id,qty:1});});if(dialog.open&&document.getElementById('dialogTitle').textContent==='My shopping cart')cart();else toast('Added '+C.product(id).name+' to your cart.');renderStore();},
 'cart-minus':id=>{change(r=>{const x=r.life.cart.find(x=>x.id===id);x.qty--;r.life.cart=r.life.cart.filter(x=>x.qty>0);});cart();renderStore();},
 'toggle-compare':id=>{if(compare.includes(id))compare=compare.filter(x=>x!==id);else if(compare.length<3)compare.push(id);else return toast('Compare up to 3 products at a time.');renderStore();},
 'compare':()=>modal('Compare products',compare.length?'<div class="grid">'+compare.map(id=>{let p=C.product(id);return '<article class="card"><h3>'+p.name+'</h3><p>'+p.tier+'</p><div class="price">'+cash(p.price)+'</div><p>Meets: '+p.tags.join(', ')+'</p><p>'+ (p.large?'Scheduled delivery':'Take home today')+'</p>'+btn('Add to cart','add-cart',id,'primary')+'</article>';}).join('')+'</div><p class="small">A basic functional product satisfies the same need. Spend more only when it fits your priorities and budget.</p>':'<p>Select two or three products using their Compare buttons.</p>'),
 'scan-shop':i=>{if(Number(i)===scanCount){scanCount++;drawCheckout();}},
 'pay-shop':()=>{if(scanCount!==scanItems.length||!scanItems.length)throw Error('Scan every item first.');const order=change(r=>{if(JSON.stringify(r.life.cart.flatMap(x=>Array.from({length:x.qty},()=>x.id)))!==JSON.stringify(scanItems))throw Error('Your cart changed. Start checkout again.');return K.checkout(r);});scanItems=[];modal('Purchase complete','<p>Paid '+cash(order.total)+' from your existing checking account.</p><p>Receipt '+esc(order.id)+'</p><p>Your move-in guide updated automatically.</p><div class="row">'+btn('Schedule large items','deliveries','','primary')+link('Return home','transition-life.html')+btn('Keep shopping','shop-scene','entrance')+'</div>');renderStore();},
 'return-item':id=>{const amount=change(r=>K.returnItem(r,id));returns();toast(cash(amount)+' returned to checking.');},
 'feedback':()=>help('Home & Beyond customer feedback'),
 'test-start':()=>{S.demo(true);render();teacher();},'test-exit':()=>{S.demo(false);close();render();},
 'test-days':d=>{if(!S.sandbox())throw Error('Test mode only.');change(r=>K.advance(r,Number(d)));teacher();},
 'test-home':()=>{if(!S.sandbox())throw Error('Test mode only.');change(r=>{if(!r.life.housing)K.acquire(r,{id:'practice',property:'Town Center Apartments',unit:'1 Bedroom',rent:800,deposit:800,status:'Approved'});});close();location.href='transition-life.html';}
};
document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(a&&S.sandbox()&&!/^(?:transition-life|home-beyond)\.html/.test(a.getAttribute('href'))){e.preventDefault();toast('Exit test mode before visiting other town pages. Your practice copy is isolated.');return;}const b=e.target.closest('[data-act]');if(!b)return;const fn=handlers[b.dataset.act];if(!fn)return;e.preventDefault();try{if(b.dataset.x&&!isStore)walk(Number(b.dataset.x),Number(b.dataset.y));fn(b.dataset.id);}catch(err){toast(err.message);}});
document.getElementById('dialogClose').onclick=close;dialog.addEventListener('cancel',()=>{if(actionTimer)clearInterval(actionTimer);actionTimer=null;cookTask=null;});
window.TTLifeUI={state,change,toast,modal,close,btn,link,esc,cash,handlers,render,captured,art};
try{if(!captured)throw Error('Choose your resident in Transition Town first.');change(r=>K.init(r));const params=new URLSearchParams(location.search);if(isStore&&params.has('dept'))shopScene=['entrance','checkout','service','employee',...C.departments.map(x=>x[0])].includes(params.get('dept'))?params.get('dept'):'exterior';if(!isStore&&sessionStorage.ttLifePlace){placing=sessionStorage.ttLifePlace;sessionStorage.removeItem('ttLifePlace');}render();if(params.has('housing'))housing();if(params.has('bills'))bills();if(params.has('teacher')&&S.teacher(captured))teacher();}catch(err){host.innerHTML='<section class="panel"><h1>Welcome to Transition Life</h1><p>'+esc(err.message)+'</p>'+link('Open Transition Town','transition-town.html','primary')+'</section>';}
let last=performance.now();setInterval(()=>{const now=performance.now(),dt=(now-last)/1000;last=now;if(document.hidden||S.name()!==captured)return;try{change(r=>K.tick(r,dt));if(window.TTLifeWork)TTLifeWork.tick(dt);}catch(e){toast(e.message);}},30000);
window.addEventListener('storage',e=>{if(e.key==='ttCurrent'&&S.name()!==captured){close();host.innerHTML='<section class="panel"><h1>The active resident changed.</h1><p>Reload to open the selected resident’s own home and belongings.</p>'+btn('Reload','reload')+'</section>';handlers.reload=()=>location.reload();}else if(e.key==='ttWorld')updateHUD();});
document.addEventListener('visibilitychange',()=>{last=performance.now();});
})();
