/* Transition Life catalog: all prices are fictional classroom simulation prices. */
(function(root){'use strict';
const departments=[['bedroom','Bedroom showroom'],['living','Living room showroom'],['kitchen','Kitchen & dining'],['bath','Bath & linens'],['cleaning','Cleaning & laundry'],['decor','Decor & entertainment']];
const products=[];
function add(id,name,dept,price,tags,room,large=false,kind=id,tier='Basic'){products.push({id,name,dept,price,tags:tags.split(','),room,large,kind,tier});}
add('mattress','Basic mattress','bedroom',299,'mattress','bedroom',true,'bed');add('mattress-standard','Standard mattress','bedroom',549,'mattress','bedroom',true,'bed','Mid-range');add('mattress-premium','Premium mattress','bedroom',999,'mattress','bedroom',true,'bed','Premium');
add('frame','Bed frame','bedroom',89,'frame','bedroom',true,'frame');add('bedset','Bed + mattress set','bedroom',699,'mattress,frame','bedroom',true,'bed','Mid-range');add('dresser','Dresser','bedroom',139,'dresser','bedroom',true,'dresser');add('nightstand','Nightstand','bedroom',39,'nightstand','bedroom',false,'table');
add('sheets','Sheet set','bedroom',19,'sheets','bedroom');add('sheets-standard','Cotton sheet set','bedroom',39,'sheets','bedroom',false,'sheets','Mid-range');add('sheets-premium','Premium sheet set','bedroom',79,'sheets','bedroom',false,'sheets','Premium');add('pillow','Pillow','bedroom',8,'pillow','bedroom');add('blanket','Blanket','bedroom',19,'blanket','bedroom');
add('couch','Compact couch','living',249,'seating,couch','living',true,'couch');add('couch-standard','Everyday couch','living',499,'seating,couch','living',true,'couch','Mid-range');add('couch-premium','Premium couch','living',899,'seating,couch','living',true,'couch','Premium');add('loveseat','Loveseat','living',299,'seating,couch','living',true,'couch');add('chair','Lounge chair','living',69,'seating','living',true,'chair');add('coffee-table','Coffee table','living',45,'coffee-table','living',true,'table');add('end-table','End table','living',29,'end-table','living',false,'table');add('tv-stand','TV stand','living',59,'tv-stand','living',true,'table');
add('dining-table','Small dining table','kitchen',79,'table','kitchen',true,'table');add('dining-chair','Dining chair','kitchen',25,'dining-chair','kitchen',true,'chair');add('dining-set','Dining table + 2 chairs','kitchen',199,'table,dining-chair','kitchen',true,'dining','Mid-range');add('dining-premium','Premium dining set','kitchen',549,'table,dining-chair','kitchen',true,'dining','Premium');
add('plate','Plate','kitchen',2,'plate','kitchen');add('bowl','Bowl','kitchen',2,'bowl','kitchen');add('cup','Cup','kitchen',1.5,'cup','kitchen');add('silverware','Fork, spoon & table knife','kitchen',4,'silverware','kitchen');add('pan','Frying pan','kitchen',14,'cookware,pan','kitchen');add('pot','Cooking pot','kitchen',18,'cookware,pot','kitchen');add('cookware-set','Pot, pan & utensil set','kitchen',39,'cookware,pan,pot,utensils','kitchen',false,'cookware','Mid-range');add('utensils','Cooking utensils','kitchen',6,'utensils','kitchen');add('containers','Food storage containers','kitchen',8,'containers','kitchen');add('toaster','Toaster','kitchen',19,'appliance','kitchen');add('microwave','Microwave','kitchen',69,'appliance','kitchen',false,'microwave','Mid-range');
add('towel','Bath towel','bath',5,'towel','bathroom');add('towel-standard','Cotton towel set','bath',18,'towel,washcloth','bathroom',false,'towel','Mid-range');add('towel-premium','Premium towel set','bath',39,'towel,washcloth','bathroom',false,'towel','Premium');add('washcloth','Washcloth','bath',1,'washcloth','bathroom');add('bathmat','Bath mat','bath',9,'bathmat','bathroom');add('toilet-paper','Toilet paper','bath',6,'toilet-paper','bathroom');add('hygiene','Soap, shampoo & toothpaste kit','bath',9,'hygiene','bathroom');add('bath-pillow','Pillow','bath',8,'pillow','bedroom');add('bath-blanket','Blanket','bath',19,'blanket','bedroom');
add('basket','Laundry basket','cleaning',8,'basket','bathroom');add('detergent','Laundry detergent','cleaning',8,'detergent','bathroom');add('cleaner','All-purpose cleaner','cleaning',3,'cleaner','bathroom');add('dish-soap','Dish soap','cleaning',2.5,'cleaner','kitchen');add('trash-can','Trash can','cleaning',12,'trash-can','kitchen');add('trash-bags','Trash bags','cleaning',6,'trash-bags','kitchen');add('broom','Broom','cleaning',9,'floor-cleaning','kitchen');add('mop','Mop','cleaning',12,'floor-cleaning','kitchen');add('vacuum','Vacuum','cleaning',59,'floor-cleaning','living',false,'vacuum','Mid-range');add('vacuum-premium','Premium vacuum','cleaning',179,'floor-cleaning','living',false,'vacuum','Premium');
add('tv','Basic television','decor',149,'tv','living',false,'tv');add('tv-standard','Smart television','decor',299,'tv','living',false,'tv','Mid-range');add('tv-premium','Premium television','decor',649,'tv','living',false,'tv','Premium');add('games','Gaming system with offline game','decor',199,'games','living',false,'console');add('lamp','Table lamp','decor',15,'lamp','any',false,'lamp');add('rug','Area rug','decor',29,'rug','living',false,'rug');add('wall-art','Wall decoration','decor',12,'decor','any',false,'art');add('mirror','Wall mirror','decor',19,'decor','any',false,'mirror');
const guide=[{title:'Must have first',items:[['mattress','Mattress / bed'],['sheets','Sheets'],['pillow','Pillow'],['blanket','Blanket'],['towel','Towels'],['washcloth','Washcloth'],['toilet-paper','Toilet paper'],['cookware','Basic cookware'],['plate','Plate'],['bowl','Bowl'],['cup','Cup'],['silverware','Fork / spoon / knife'],['trash-bags','Trash bags'],['food','Basic groceries'],['hygiene','Personal hygiene supplies']]},{title:'Need soon',items:[['seating','Couch / chair'],['table','Dining table'],['dining-chair','Dining chairs'],['basket','Laundry basket'],['detergent','Laundry detergent'],['cleaner','Cleaning products'],['floor-cleaning','Broom / mop / vacuum'],['containers','Food storage containers'],['extra-cookware','Additional cookware']]},{title:'Nice to have',items:[['tv','Television'],['games','Gaming system'],['decor','Decorations'],['rug','Rugs'],['lamp','Lamps'],['upgrade','Upgraded furniture'],['appliance','Extra appliances']]}];
const roles=[['cashier','Cashier',13],['sales','Sales Associate',13],['stock','Stock Associate',13],['furniture','Furniture Associate',14],['service','Customer Service Associate',14],['pickup','Order Pickup Associate',13],['warehouse','Warehouse Associate',14],['delivery','Delivery Team / Delivery Driver',15]].map(([id,name,wage])=>({id,name,wage}));
const recipes=[{id:'eggs',name:'Scrambled eggs',ingredients:{eggs:1,butter:1},tools:['pan','utensils','plate'],hunger:30,steps:['Wash hands','Add butter to pan','Crack and stir eggs','Cook until firm','Turn off stove','Plate the eggs']},{id:'toast',name:'Skillet toast',ingredients:{bread:1,butter:1},tools:['pan','utensils','plate'],hunger:20,steps:['Wash hands','Butter the bread','Toast in pan','Turn off stove','Plate the toast']},{id:'eggs-toast',name:'Eggs & toast',ingredients:{eggs:1,bread:1,butter:1},tools:['pan','utensils','plate'],hunger:50,steps:['Wash hands','Butter the pan','Cook eggs until firm','Toast the bread','Turn off stove','Plate the meal']},{id:'pasta',name:'Pasta with sauce',ingredients:{pasta:1,sauce:1},tools:['pot','utensils','bowl'],hunger:45,steps:['Wash hands','Fill pot with water','Boil pasta','Drain carefully','Add and heat sauce','Turn off stove','Serve in bowl']},{id:'chicken',name:'Chicken & vegetables',ingredients:{chicken:1,vegetables:1},tools:['pan','utensils','plate'],hunger:55,steps:['Wash hands','Prepare vegetables','Place chicken in pan','Cook chicken to 165°F','Wash used surfaces','Turn off stove','Plate the meal']}];
const api={departments,products,guide,roles,recipes,product:id=>products.find(p=>p.id===id)};if(typeof module!=='undefined')module.exports=api;else root.TTLifeCatalog=api;
})(typeof window!=='undefined'?window:globalThis);
