/* Extends ttWorld.residents[name].life. Never creates a profile or starting balance. */
(function(root){'use strict';
const C=typeof module!=='undefined'?require('./catalog.js'):root.TTLifeCatalog;
const clone=x=>JSON.parse(JSON.stringify(x)),money=x=>Math.round(Number(x)*100)/100,dayms=86400000;
const dateDay=()=>new Date().toISOString().slice(0,10),plusDays=(d,n)=>new Date(Date.parse(d+'T12:00:00Z')+n*dayms).toISOString().slice(0,10);
const diffDays=(a,b)=>Math.floor((Date.parse(a+'T12:00:00Z')-Date.parse(b+'T12:00:00Z'))/dayms);
const utilSpecs={electric:{name:'Electric',deposit:200,monthly:85},water:{name:'Water',deposit:160,monthly:45},gas:{name:'Gas',deposit:100,monthly:55},internet:{name:'Internet',deposit:0,monthly:65}};
function init(r){
 if(!r||!Number.isFinite(Number(r.checking)))throw Error('Open your existing Transition Town profile first.');
 if(!r.life)r.life={version:1,date:dateDay(),needs:{hunger:85,energy:85,hygiene:85,fun:80},inventory:[],food:[],meals:[],orders:[],cart:[],bills:[],ledger:[],actions:[],room:'living',avatar:{x:50,y:79},introSeen:false,training:{}};
 const l=r.life;['inventory','food','meals','orders','cart','bills','ledger','actions'].forEach(k=>{if(!Array.isArray(l[k]))l[k]=[]});l.training=l.training||{};r.utilities=r.utilities||{};
 // A legacy purchased/rented home is honored without charging or giving furniture.
 if(!l.housing&&typeof r.home==='string'&&r.home.trim()&&!/^(not selected|none|needs|no home)/i.test(r.home)){
 const match=r.home.match(/\$([\d,]+)(?:\/|\s*per\s*)month/i);const rent=match?Number(match[1].replace(/,/g,'')):0;
 l.housing={id:'legacy',name:r.home,tenure:/mortgage|owned|bought/i.test(r.home)?'owner':'renter',monthly:rent,acquired:l.date,legacy:true,gas:false};
 if(rent)addBill(l,l.housing.tenure==='owner'?'mortgage':'rent',rent,plusDays(l.date,30));
 }
 if(l.housing)for(const [k,s]of Object.entries(utilSpecs)){if(r.utilities[k+'On']&&!l.bills.some(b=>b.kind===k)){addBill(l,k,s.monthly,plusDays(l.date,30));}}
 return l;
}
function log(r,amount,description){const l=init(r);l.ledger.unshift({id:uid(),date:l.date,amount:money(amount),description});r.history=r.history||[];r.history.push(description+(amount?' '+(amount>0?'+':'')+'$'+money(amount).toFixed(2):''));}
function debit(r,amount,description){amount=money(amount);if(!Number.isFinite(amount)||amount<0)throw Error('Invalid payment.');if(Number(r.checking)<amount)throw Error('Not enough money in checking. Review your cart or visit the bank.');r.checking=money(Number(r.checking)-amount);log(r,-amount,description);}
function uid(){return Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10);}
function has(r,tag,delivered=false){const l=init(r);if(tag==='food')return l.food.some(x=>x.qty>0);if(tag==='extra-cookware')return l.inventory.filter(x=>x.tags.includes('cookware')&&!x.returned).reduce((a,x)=>a+x.qty,0)>1;if(tag==='upgrade')return l.inventory.some(x=>x.tier!=='Basic'&&!x.returned);return l.inventory.some(x=>!x.returned&&x.qty>0&&x.tags.includes(tag)&&(!delivered||!x.deliveryPending));}
function placed(r,tag){return init(r).inventory.some(x=>x.qty>0&&!x.returned&&!x.deliveryPending&&x.placement&&x.tags.includes(tag));}
function addBill(l,kind,amount,due){const bill={id:uid(),kind,amount:money(amount),due,paid:false,autopay:false,lateFee:0};l.bills.push(bill);return bill;}
function stage(b,l){if(b.paid)return 'PAID';const d=diffDays(l.date,b.due);if(d<0)return 'UPCOMING';if(d===0)return b.kind==='mortgage'?'MORTGAGE DUE':'DUE';if(b.kind==='rent'){return d>=45?'POSSIBLE EVICTION':d>=30?'HOUSING AT RISK':d>=21?'FINAL NOTICE':d>=14?'WARNING NOTICE':d>=7?'LATE FEE':'PAST DUE';}if(b.kind==='mortgage')return d>=90?'FORECLOSURE RISK':d>=60?'SERIOUS DELINQUENCY':d>=30?'DELINQUENT':'PAST DUE';return d>=21?'DISCONNECTED':d>=14?'FINAL NOTICE':'PAST DUE';}
function billTotal(b,l){return money(b.amount+(!b.paid&&diffDays(l.date,b.due)>=7?(b.kind==='rent'?25:15):0));}
function processBills(r){const l=init(r);
 // Keep every monthly invoice visible, even when an older one remains unpaid.
 for(const kind of new Set(l.bills.map(b=>b.kind))){let last=l.bills.filter(b=>b.kind===kind).sort((a,b)=>a.due.localeCompare(b.due)).at(-1);let count=0;while(diffDays(l.date,last.due)>=0&&count++<120){const next=addBill(l,kind,last.amount,plusDays(last.due,30));next.autopay=last.autopay;last=next;}}
 for(const b of l.bills.slice()){if(b.paid)continue;const d=diffDays(l.date,b.due);if(b.autopay&&d>=0&&Number(r.checking)>=billTotal(b,l)){payBill(r,b.id);continue;}if(utilSpecs[b.kind]&&d>=21)r.utilities[b.kind+'On']=false;}}
function payBill(r,id){const l=init(r),b=l.bills.find(x=>x.id===id);if(!b||b.paid)throw Error('This bill is already paid or unavailable.');const amount=billTotal(b,l);debit(r,amount,(utilSpecs[b.kind]?.name||b.kind)+' bill');b.paid=true;b.paidOn=l.date;b.totalPaid=amount;
 if(utilSpecs[b.kind])r.utilities['last'+b.kind[0].toUpperCase()+b.kind.slice(1)+'Paid']=r.sessions||0;
 let due=plusDays(b.due,30);if(!l.bills.some(x=>x.kind===b.kind&&x.due===due))addBill(l,b.kind,b.amount,due).autopay=b.autopay;
 return amount;
}
function utility(r,kind){const l=init(r),s=utilSpecs[kind];if(!l.housing)throw Error('Obtain housing before setting up utilities.');if(!s||kind==='gas'&&!l.housing.gas)throw Error('This property does not require gas.');if(r.utilities[kind+'On'])throw Error('This service is already active.');if(l.bills.some(b=>b.kind===kind&&!b.paid&&diffDays(l.date,b.due)>=0))throw Error('Pay the outstanding '+s.name.toLowerCase()+' bills before reconnecting.');const previously=!!r.utilities[kind+'Deposit'];const cost=previously?25:s.deposit;debit(r,cost,s.name+(previously?' reconnection':' setup deposit'));r.utilities[kind+'Deposit']=true;r.utilities[kind+'On']=true;r.utilities['last'+kind[0].toUpperCase()+kind.slice(1)+'Paid']=r.sessions||0;if(!l.bills.some(b=>b.kind===kind&&!b.paid))addBill(l,kind,s.monthly,plusDays(l.date,30));return cost;}
function acquire(r,app){const l=init(r);if(l.housing)throw Error('You already have housing. Your current home is preserved.');if(app.status!=='Approved')throw Error('Miss Kayla must approve this housing application first.');if(app.closed)throw Error('This housing agreement was already completed.');const owner=app.tenure==='owner',rent=Number(app.rent),price=Number(app.price),down=Number(app.down);
 const amount=owner?(app.financing==='Cash purchase'?price:down):rent+Number(app.deposit??rent);if(!Number.isFinite(amount)||amount<=0)throw Error('Housing terms are incomplete.');
 if(owner&&(!Number.isFinite(price)||price<=0||down<price*.03||down>price))throw Error('Review the purchase price and down payment with Miss Kayla.');
 debit(r,amount,owner?'Home closing: '+app.property:'First month + deposit: '+app.property);const principal=owner&&app.financing!=='Cash purchase'?money(price-down):0,rate=.06/12,monthly=owner?(principal?money(principal*rate/(1-Math.pow(1+rate,-360))):0):rent;
 l.housing={id:app.id||uid(),name:app.property+(app.unit?' — '+app.unit:''),tenure:owner?'owner':'renter',monthly,acquired:l.date,gas:!!app.gas,principal,rate:principal?.06:0,deposit:owner?down:Number(app.deposit??rent)};r.home=l.housing.name;app.closed=true;app.status='Moved in';app.resident=app.student||app.resident;app.completed=l.date;if(monthly)addBill(l,owner?'mortgage':'rent',monthly,plusDays(l.date,30));l.keysPending=true;return l.housing;}
function checkout(r){const l=init(r);if(!l.cart.length)throw Error('Your cart is empty.');const items=l.cart.map(x=>{const p=C.product(x.id);if(!p||!Number.isInteger(x.qty)||x.qty<1||x.qty>99)throw Error('Review your cart.');return {p,qty:x.qty};});const total=money(items.reduce((s,x)=>s+x.p.price*x.qty,0));debit(r,total,'Home & Beyond purchase');const order={id:uid(),date:l.date,total,status:'Paid',items:[],delivery:null};for(const {p,qty}of items){const item={...clone(p),uid:uid(),qty,orderId:order.id,deliveryPending:p.large,placement:null,returned:false,used:false};l.inventory.push(item);order.items.push({uid:item.uid,id:p.id,qty,price:p.price});}l.orders.push(order);l.cart=[];return order;}
function schedule(r,id,date,window){const l=init(r),o=l.orders.find(x=>x.id===id);if(!l.housing)throw Error('Choose housing first so the delivery team has an address.');if(!o||o.delivery)throw Error('This order is already scheduled.');if(!o.items.some(x=>l.inventory.find(i=>i.uid===x.uid)?.deliveryPending))throw Error('This order does not need delivery.');if(!['Morning','Afternoon'].includes(window)||diffDays(date,l.date)<1||diffDays(date,l.date)>30)throw Error('Choose a delivery day in the next 30 simulation days.');o.delivery={date,window,address:l.housing.name,status:'Scheduled',fee:0};return o;}
function receive(r,id){const l=init(r),o=l.orders.find(x=>x.id===id);if(!o?.delivery||diffDays(l.date,o.delivery.date)<0)throw Error('The delivery is not due yet.');if(o.delivery.status==='Delivered')throw Error('Already delivered.');o.delivery.status='Delivered';o.items.forEach(x=>{let item=l.inventory.find(i=>i.uid===x.uid);if(item)item.deliveryPending=false;});log(r,0,'Received furniture delivery '+o.id);}
function place(r,id,room,x,y){const l=init(r),i=l.inventory.find(x=>x.uid===id);if(!l.housing||!i||i.returned||i.deliveryPending)throw Error('This item is not ready to place.');if(i.room!=='any'&&i.room!==room)throw Error('Place this item in the '+i.room+'.');if(!['bedroom','kitchen','bathroom','living'].includes(room)||!Number.isFinite(x)||!Number.isFinite(y))throw Error('Choose a room location.');i.placement={room,x:Math.max(12,Math.min(87,x)),y:Math.max(57,Math.min(84,y))};}
function returnItem(r,uid){const l=init(r),i=l.inventory.find(x=>x.uid===uid);if(!i||i.returned||i.used||i.placement||diffDays(l.date,l.orders.find(o=>o.id===i.orderId)?.date||l.date)>30)throw Error('Returns require an unused, unplaced item within 30 simulation days.');i.returned=true;i.deliveryPending=false;const amount=money(i.price*i.qty);r.checking=money(Number(r.checking)+amount);log(r,amount,'Home & Beyond return: '+i.name);return amount;}
function groceryTag(name){const n=name.toLowerCase();if(/egg/.test(n)&&!/noodle/.test(n))return 'eggs';if(/butter/.test(n))return 'butter';if(/bread|bun|loaf/.test(n))return 'bread';if(/rotisserie|prepared|salad bowl|fried chicken/.test(n))return 'ready';if(/chicken/.test(n))return 'chicken';if(/pasta sauce/.test(n))return 'sauce';if(/pasta|spaghetti|rotini|noodle|macaroni/.test(n))return 'pasta';if(/vegetable|broccoli|carrot|pepper|lettuce|tomato|corn|celery|cucumber/.test(n))return 'vegetables';if(/milk/.test(n))return 'milk';if(/apple|banana|orange|grape|peach|berry|berries|fruit/.test(n))return 'fruit';if(/cereal|oatmeal|flakes|crunch/.test(n))return 'cereal';if(/chips|cracker|cookie|pretzel|snack/.test(n))return 'snack';return 'other';}
function ingestGroceries(r,items,receipt){const l=init(r);if(l.actions.some(a=>a.receipt===receipt))return;for(const x of items){const dept=String(x.key||'').split('-')[0];if(['12','13','14'].includes(dept)){let tag=/trash bags/i.test(x.name)?'trash-bags':/toilet paper/i.test(x.name)?'toilet-paper':/detergent/i.test(x.name)?'detergent':/plate/i.test(x.name)?'plate':/shampoo|wash|tooth|soap|deodorant|lotion/i.test(x.name)&&dept==='14'?'hygiene':'cleaner';l.inventory.push({uid:uid(),id:'grocery-'+x.key,name:x.name,qty:x.qty,tags:[tag],room:'any',kind:'supplies',price:x.price,tier:'Basic',orderId:receipt,deliveryPending:false,returned:false});}else{const tag=groceryTag(x.name),qty=x.qty*({eggs:6,bread:6,butter:8,pasta:4,sauce:4,milk:4,cereal:4}[tag]||2);l.food.push({id:uid(),name:x.name,tag,qty,receipt,raw:['chicken'].includes(tag)||/raw|beef|pork|fish|salmon|shrimp/i.test(x.name)});}}l.actions.push({receipt,type:'grocery',date:l.date});}
function recipeAvailable(r,id){const l=init(r),recipe=C.recipes.find(x=>x.id===id);if(!recipe)return false;return Object.entries(recipe.ingredients).every(([tag,n])=>l.food.filter(f=>f.tag===tag).reduce((s,x)=>s+x.qty,0)>=n)&&recipe.tools.every(t=>has(r,t,true));}
function cook(r,id){const l=init(r);if(!l.housing)throw Error('Obtain housing before using your home kitchen.');const recipe=C.recipes.find(x=>x.id===id);if(!recipeAvailable(r,id))throw Error('You need the ingredients and cookware shown.');if(!r.utilities.waterOn)throw Error('Connect water to wash and cook.');if(!(l.housing?.gas?r.utilities.gasOn:r.utilities.electricOn))throw Error('Your stove needs active '+(l.housing?.gas?'gas':'electricity')+'.');for(const [tag,n]of Object.entries(recipe.ingredients)){let left=n;for(const f of l.food.filter(f=>f.tag===tag)){let take=Math.min(left,f.qty);f.qty-=take;left-=take;}}l.inventory.filter(i=>!i.returned&&!i.deliveryPending&&recipe.tools.some(t=>i.tags.includes(t))).forEach(i=>i.used=true);l.meals.push({id:uid(),name:recipe.name,hunger:recipe.hunger});log(r,0,'Cooked '+recipe.name);}
function eat(r,id,meal=false){const l=init(r),list=meal?l.meals:l.food,i=list.find(x=>x.id===id);if(!i||(!meal&&i.qty<1))throw Error('That food is no longer available.');if(!meal&&(i.raw||!['fruit','bread','snack','ready','cereal','milk'].includes(i.tag)))throw Error('Prepare this ingredient at the stove first.');if(meal)list.splice(list.indexOf(i),1);else i.qty--;l.needs.hunger=Math.min(100,l.needs.hunger+(meal?i.hunger:20));log(r,0,'Ate '+i.name);}
function action(r,kind){const l=init(r);if(!l.housing)throw Error('Obtain housing first.');const n=l.needs;if(['shower','bath','sink','clean'].includes(kind)&&!r.utilities.waterOn)throw Error('You cannot '+(kind==='shower'?'shower':kind==='bath'?'take a bath':'use water')+' because your water service is currently disconnected.');if(['tv','games'].includes(kind)){if(!placed(r,kind))throw Error('Purchase and place a '+(kind==='tv'?'TV':'gaming system')+' first.');if(!r.utilities.electricOn)throw Error('Connect electricity to use this item.');}if(['nap','bed','night'].includes(kind)&&!placed(r,'mattress'))throw Error('Place your delivered mattress in the bedroom first.');
 if(kind==='floor')n.energy=Math.max(n.energy,Math.min(65,n.energy+22));if(kind==='nap')n.energy=Math.min(100,n.energy+30);if(kind==='bed')n.energy=Math.min(100,n.energy+55);if(kind==='night'){n.energy=100;advance(r,1);n.hunger=Math.max(0,n.hunger-12);}if(kind==='floor-night'){n.energy=Math.max(n.energy,Math.min(65,n.energy+22));advance(r,1);n.hunger=Math.max(0,n.hunger-12);}if(kind==='shower'||kind==='bath')n.hygiene=Math.min(100,n.hygiene+(has(r,'hygiene',true)?55:25));if(kind==='sink')n.hygiene=Math.min(100,n.hygiene+10);if(kind==='tv'||kind==='games')n.fun=Math.min(100,n.fun+30);if(kind==='relax')n.fun=Math.min(100,n.fun+12);if(kind==='clean'){if(!has(r,'cleaner',true))throw Error('Buy cleaning supplies first.');l.clean=true;n.hygiene=Math.min(100,n.hygiene+10);}l.inventory.filter(i=>i.placement).forEach(i=>{if((['bed','night','nap'].includes(kind)&&i.tags.includes('mattress'))||i.tags.includes(kind)||(['relax'].includes(kind)&&i.tags.includes('seating')))i.used=true;});if(['shower','bath'].includes(kind))l.inventory.filter(i=>!i.returned&&i.tags.includes('hygiene')).forEach(i=>i.used=true);if(kind==='clean')l.inventory.filter(i=>!i.returned&&i.tags.includes('cleaner')).forEach(i=>i.used=true);log(r,0,'Home: '+kind);}
function advance(r,days=1){const l=init(r);if(!Number.isInteger(days)||days<1||days>120)throw Error('Invalid simulation time.');for(let i=0;i<days;i++){l.date=plusDays(l.date,1);processBills(r);}}
function tick(r,seconds){const l=init(r);seconds=Math.min(60,Math.max(0,seconds));const rates={hunger:.8,energy:.5,hygiene:.4,fun:.6};for(const k of Object.keys(rates))l.needs[k]=Math.max(0,l.needs[k]-rates[k]*seconds/60);}
function alerts(r){const l=init(r),a=[];if(!l.housing)return ['Housing not yet obtained'];if(!has(r,'mattress'))a.push('No Bed Purchased');if(l.food.reduce((s,x)=>s+x.qty,0)+l.meals.length*2<4)a.push('Very Low Food Supply');for(const b of l.bills.filter(x=>!x.paid)){const status=stage(b,l);if(['HOUSING AT RISK','POSSIBLE EVICTION','FORECLOSURE RISK'].includes(status))a.push(status);if(diffDays(l.date,b.due)>0)a.push((utilSpecs[b.kind]?.name||b.kind)+' Bill '+status);}if(['water','electric'].some(k=>!r.utilities[k+'Deposit']&&!r.utilities[k+'On']))a.push('Utilities Not Set Up');if(['water','electric'].some(k=>r.utilities[k+'Deposit']&&!r.utilities[k+'On']))a.push('Utilities Disconnected');return a.length?a:['Doing Well'];}
const api={init,money,uid,clone,dateDay,plusDays,diffDays,utilSpecs,has,placed,debit,log,addBill,stage,billTotal,processBills,payBill,utility,acquire,checkout,schedule,receive,place,returnItem,ingestGroceries,recipeAvailable,cook,eat,action,advance,tick,alerts};if(typeof module!=='undefined')module.exports=api;else root.TTLifeCore=api;
})(typeof window!=='undefined'?window:globalThis);
