/* Additive hooks for existing Town navigation, housing, utilities and recreation. */
(function(){'use strict';const K=TTLifeCore,S=TTLifeStore;
const style=document.createElement('style');style.textContent='.ttLifeMarketPlot{max-width:1100px;margin:16px auto 0;padding:18px;background:linear-gradient(#536960 0 16px,#c2baa5 16px 25px,#688157 25px);border-radius:14px;text-align:center;color:white}.ttLifeMarketPlot a{display:block;width:min(480px,100%);margin:auto;color:#fff;text-decoration:none;background:#134d51;padding:8px;border:3px solid #d8b56e;border-radius:16px}.ttLifeMarketPlot img{display:block;width:100%;border-radius:10px}.ttLifeMarketPlot strong{display:block;padding:9px;font:700 21px Georgia}.ttLifeMarketPlot p{margin:8px;font:14px Arial}.ttLifeQuick{display:flex;gap:8px;flex-wrap:wrap;padding:12px 0}.ttLifeQuick a{display:inline-block;background:#185c5e;color:white;padding:12px;border-radius:12px;text-decoration:none;font-weight:700}';document.head.appendChild(style);
const directory=document.getElementById('townDirectory');if(directory){let b=document.createElement('button');b.textContent='My Home · Transition Life';b.onclick=()=>{if(need())location.href='transition-life.html';};directory.appendChild(b);let store=document.createElement('button');store.textContent='Home & Beyond · Now Hiring';store.onclick=()=>{if(need())location.href='home-beyond.html';};directory.appendChild(store);}
// The original illustrated map has no unused large building footprint. Its open outer edge
// is extended inside the existing map viewport; original art and hitboxes stay untouched.
const map=document.querySelector('.townmap');if(map){const lot=document.createElement('section');lot.className='ttLifeMarketPlot';lot.setAttribute('aria-label','Home & Beyond building at the south edge of Transition Town');lot.innerHTML='<p>South Market · Home & Beyond</p><a href="home-beyond.html" aria-label="Enter Transition Town Home & Beyond"><img src="transition-life/assets/store-exterior.webp" alt="Home & Beyond home goods store with Now Hiring sign" loading="lazy"><strong>HOME & BEYOND</strong><span>Shop for your home · Apply for a job</span></a>';map.insertAdjacentElement('afterend',lot);}
function links(target,html){const el=document.querySelector(target);if(!el)return;let row=document.createElement('div');row.className='ttLifeQuick';row.innerHTML=html;el.appendChild(row);}
const homeLinks='<a href="transition-life.html">Enter my home</a><a href="transition-life.html?housing=1">Housing applications / Get my keys</a><a href="home-beyond.html">Home & Beyond</a>';
const teacherLink='<a href="transition-life.html?teacher=1">Transition Life / Housing overview</a>';
function wrap(name,after){const original=window[name];if(typeof original!=='function')return;window[name]=function(...args){const result=original.apply(this,args);after(...args);return result;};}
wrap('housingMenu',()=>links('#content',homeLinks));wrap('profile',()=>links('#content',homeLinks));wrap('teacher',()=>links('#content',teacherLink));wrap('teacherResidents',()=>links('#content',teacherLink));
wrap('townJobs',()=>links('#centerScene .roomwrap','<a href="home-beyond.html?dept=employee">Home & Beyond · Apply / Employee Center</a>'));
wrap('townShops',()=>links('#content','<a href="home-beyond.html">Home & Beyond · Home Goods Store</a>'));
wrap('renderResidentDashboard',()=>{const box=document.getElementById('residentDashboard')||document.querySelector('#kaylaInformation');if(!box||box.querySelector('[data-life-dashboard]'))return;const b=document.createElement('button');b.dataset.lifeDashboard='1';b.textContent=S.teacher(S.name())?'Transition Life overview':'Enter my home';b.onclick=()=>location.href='transition-life.html'+(S.teacher(S.name())?'?teacher=1':'');box.appendChild(b);});
const originalDept=window.cityDept;window.cityDept=function(kind){try{const r=S.read().residents[S.name()];if(['water','electric'].includes(kind)&&r?.life?.housing){location.href='transition-life.html?bills=1';return;}}catch(e){}return originalDept(kind);};
// Use the same household invoices from every legacy utility action after moving in.
for(const name of ['utilityApplication','utilityPay','utilityEarlyPay','utilityLatePay','utilityDisconnect']){const old=window[name];window[name]=function(...args){try{const r=S.read().residents[S.name()];if(r?.life?.housing){location.href='transition-life.html?bills=1';return;}}catch(e){}return old.apply(this,args);};}
let last=Date.now();setInterval(()=>{const now=Date.now(),seconds=Math.min(10,(now-last)/1000);last=now;if(document.hidden)return;if(!document.querySelector('#transitionParkScene,#transitionPlaygroundScene,#parkGame,#ttSportOverlay,#recreationZone'))return;try{const n=S.name(),w=S.read(),r=w.residents[n];if(!r?.life)return;r.life.needs.fun=Math.min(100,r.life.needs.fun+seconds/15);S.write(w,n);}catch(e){}},10000);
const route=new URLSearchParams(location.search).get('life');if(route)setTimeout(()=>{if(!need())return;const routes={park:transitionPark,bank:bankLobby,housing:housingMenu,assistance:riverviewApartments,jobs:townJobs,'job-review':()=>{if(S.teacher(S.name()))teacherApplications();}};if(routes[route])routes[route]();},0);
try{renderResidentDashboard();if(S.teacher(S.name())&&document.querySelector('#sheet.show'))links('#content',teacherLink);}catch(e){}
})();
