(function(){'use strict';const U=TTLifeUI,C=TTLifeCatalog,K=TTLifeCore,S=TTLifeStore,W=TTLifeWorkCore,{btn,esc,cash}=U;let visible=false;
const instructions={cashier:'Scan every item. Enter the cash the customer gives you. Count exact change in the cash drawer, then offer a polite closing and receipt.',sales:'Read the customer’s needs and spending limit. Select useful products, compare the total, and explain your recommendation.',furniture:'Help a customer furnish a room within a budget. Select the essential furniture and explain why it fits.',stock:'Read the shipment label. Place the item in the correct department, face three shelf positions, and enter the number stocked.',service:'Check the receipt and 30-day return policy. Enter the refund for an eligible item, or route an older return to the manager. Write a professional response.',pickup:'Read the customer ticket. Locate the matching order, scan its items, verify the pickup code, and attach the customer label.',warehouse:'Find the manifest, scan the products into the shipment, seal three packing points and verify the destination label.',delivery:'Prepare the correct customer shipment, verify the destination and secure all three load points. Driving practice uses the existing simulator; this shift covers dispatch preparation.'};
function jobs(){U.modal('Now hiring • Home & Beyond','<p>Apply through Transition Town’s existing teacher review process. Training is available before you are hired, but practice does not pay wages.</p><div class="grid">'+C.roles.map(r=>'<article class="card"><h3>'+r.name+'</h3><p>'+cash(r.wage)+'/hour · simulated</p><p class="small">'+instructions[r.id]+'</p><div class="row">'+btn('Apply','job-apply',r.id,'primary')+btn('Try training','training',r.id)+'</div></article>').join('')+'</div>');}
function apply(role){const p=C.roles.find(x=>x.id===role);U.modal('Apply • '+p.name,'<p>Uses your existing resident profile: <b>'+esc(U.captured)+'</b>. Use fictional town information.</p><label>Availability<input id="jobAvailability" placeholder="Days and times you can work"></label><label>Relevant skills<textarea id="jobSkills" rows="2"></textarea></label><label>Why this role?<textarea id="jobWhy" rows="3"></textarea></label>'+btn('Submit for Miss Kayla review','job-submit',role,'primary'));}
function applications(){const a=(U.state().r.applications||[]).filter(x=>x.employer==='Home & Beyond');U.modal('My Home & Beyond applications',a.length?a.map(x=>'<div class="card"><h3>'+esc(x.job)+'</h3><p>'+esc(x.status)+'</p>'+(x.status==='Interview Requested'?'<label>Your interview response<textarea id="interview-'+esc(x.id)+'" placeholder="Tell us how you would help a customer with a tight budget."></textarea>'+btn('Save interview response','interview-save',x.id):'')+'</div>').join(''):'<p>No applications yet.</p>'+btn('View openings','jobs','','primary'));}
function center(){visible=false;const {r,l}=U.state(),e=r.employment?.homeBeyond,w=l.work;if(w?.training&&w.task.complete&&l.training[w.role]&&!w.closed){U.change(r=>r.life.work.closed=true);return center();}U.modal('Employee time clock','<img class="work-scene" src="transition-life/assets/store-employee.webp" alt="Home & Beyond employee training and time clock"><p><b>Schedule:</b> '+esc(e?.schedule||'Apply and discuss your schedule with Miss Kayla.')+'</p><p><b>Assignment:</b> '+esc(e?.position||'Not hired yet')+'</p><div class="row">'+(w&&!w.closed?btn(w.training?'Resume practice':'Resume current shift','work-resume','','primary')+btn('End without pay','work-stop'):'')+(e?.active&&(!w||w.closed)?btn('Clock in','clock-in',e.role,'primary'):'')+btn('Applications','applications')+'</div><h3 style="margin-top:20px">Short training & practice</h3><div class="row">'+C.roles.map(x=>btn((l.training[x.id]?'✓ ':'')+x.name,'training',x.id)).join('')+'</div><p class="small">Five active real minutes = one eight-hour simulated shift. Six verified tasks are also required. Breaks pause the active work timer. A shift can be paid only once.</p>');}
function training(role){U.modal('Training • '+C.roles.find(x=>x.id===role).name,'<p id="trainingText">'+instructions[role]+'</p><p>Do three practice tasks to complete this role’s training. You can retry mistakes.</p><div class="row">'+btn('Read aloud','work-read',role)+btn('Start hands-on practice','practice-start',role,'primary')+'</div>');}
function start(role,training){U.change(r=>W.start(r,role,training));draw();}
function attempt(action,data){let problem=null;U.change(r=>{try{W.input(r,action,data);}catch(e){problem=e.message;}});if(problem)U.toast(problem);draw();}
function draw(){visible=true;const {l}=U.state(),w=l.work;if(!w||w.closed)return center();const t=w.task,role=C.roles.find(x=>x.id===w.role),scene=['cashier'].includes(w.role)?'checkout':['stock','warehouse','delivery'].includes(w.role)?'cleaning':['sales','furniture'].includes(w.role)?'bedroom':'service';
 let html='<img class="work-scene" src="transition-life/assets/store-'+scene+'.webp" alt="Your Home & Beyond work area"><p class="work-progress" id="workProgress">'+(w.training?'Training':'On the clock')+' · '+w.done+' tasks verified · '+Math.floor(w.elapsed)+' / 300 active seconds</p>';
 if(t.complete){html+='<h3>Task verified.</h3><p>'+esc(w.training&&l.training[w.role]?'Training complete. You can now work this role after Miss Kayla hires you.':'Your work was recorded.')+'</p><div class="row">'+btn('Next customer / task','work-next','','primary')+btn(w.training?'Return to employee center':'Break / schedule','employee')+(!w.training?btn('Clock out & receive earned pay','work-pay'):'')+'</div>';if(w.role==='delivery')html+='<p>'+U.link('Driver training practice','driving-simulator-game.html')+'</p><p class="small">The current driving route is a separate training exercise. Live furniture delivery routes and cross-device delivery assignments are future connections.</p>';U.modal(role.name,html);return;}
 if(w.role==='cashier')html+='<div class="task-ticket">Customer hands you <b>'+cash(t.tender)+'</b> in cash.</div><div class="scan-belt">'+t.items.map((id,i)=>'<button data-act="work-scan" data-id="'+i+'" class="'+(i<t.scanned.length?'scanned':'')+'" '+(i!==t.scanned.length?'disabled':'')+'>'+'<span class=work-product>'+U.art(C.product(id))+'</span>'+C.product(id).name+'<br>'+cash(C.product(id).price)+'</button>').join('')+'</div><p>Register total: <b>'+cash(t.total)+'</b></p>'+(t.stage===0?'<label>Cash received<input id="cashReceived" type="number" step=".01" inputmode="decimal"></label>'+btn('Accept cash','work-tender','','primary'):'<p>Change in tray: <b>'+cash(t.change)+'</b></p><div class="row">'+[20,10,5,1,.25,.1,.05,.01].map(v=>btn(cash(v),'work-change',v)).join('')+btn('Clear tray','work-change',-1)+'</div><label>Customer-service closing<input id="customerClosing" placeholder="What will you say when giving the receipt?"></label>'+btn('Give change & receipt','work-receipt','','primary'));
 if(w.role==='sales'||w.role==='furniture'){const candidates=C.products.filter(p=>p.tags.some(tag=>t.tags.includes(tag))),total=t.selected.reduce((s,id)=>s+C.product(id).price,0);html+='<div class="task-ticket"><b>'+t.customer+'</b><p>'+t.need+'</p></div><p>Selected total: <b>'+cash(total)+'</b> / '+cash(t.budget)+'</p><div class="grid">'+candidates.map(p=>'<button class="'+(t.selected.includes(p.id)?'selected':'')+'" data-act="work-select" data-id="'+p.id+'">'+'<span class=work-product>'+U.art(p)+'</span>'+p.name+'<br>'+cash(p.price)+'</button>').join('')+'</div><label>Explain your recommendation<textarea id="recommendation" rows="3" placeholder="Explain the essential items and how they fit the budget."></textarea></label>'+btn('Present recommended products','work-recommend','','primary');}
 if(w.role==='stock')html+='<div class="task-ticket"><span class=work-product>'+U.art(C.product(t.product))+'</span><b>Shipment: '+t.quantity+' × '+C.product(t.product).name+'</b><p>Select the correct department shelf.</p></div><div class="grid">'+C.departments.map(([id,name])=>'<button class="dropzone" data-act="work-shelf" data-id="'+id+'">'+name+(t.stage===1&&id===C.product(t.product).dept?' ✓ Stocked':'')+'</button>').join('')+'</div>'+(t.stage===1?'<p>Face each shelf position: '+t.faced+'/3</p><div class="scan-belt">'+[0,1,2].map(i=>btn('<span class="work-product '+(i<t.faced?'faced':'unfaced')+'">'+U.art(C.product(t.product))+'</span>'+(i<t.faced?'Facing forward':'Turn product forward'),'work-face',i,i<t.faced?'scanned':'')).join('')+'</div><label>Units stocked<input id="stockQuantity" type="number" inputmode="numeric"></label>'+btn('Record inventory count','work-stock-finish','','primary'):'');
 if(w.role==='service')html+='<div class="task-ticket"><b>Customer: “'+t.reason+'”</b><p>Unused '+C.product(t.product).name+' · bought '+t.days+' simulation days ago</p><p>Receipt price '+cash(C.product(t.product).price)+'</p></div><p>Policy: unused items with a receipt can be returned within 30 days. Ask the manager to review older returns.</p><label>Route this request<select id="returnDecision"><option value="">Choose a workflow</option><option value="refund">Return / refund to original payment</option><option value="manager">Manager review</option></select></label><label>Refund amount (if eligible)<input id="refundAmount" type="number" step=".01" inputmode="decimal"></label><label>Professional response<textarea id="serviceResponse" rows="3"></textarea></label>'+btn('Submit service record','work-service','','primary');
 if(['pickup','warehouse','delivery'].includes(w.role))html+='<div class="task-ticket"><b>'+t.customer+' · Order '+t.order+'</b><p>Verification code '+t.code+'</p><p>Manifest: '+t.items.map(id=>C.product(id).name).join(' + ')+'</p></div><h3>Find the order on the rack</h3><div class="row">'+t.rack.map(id=>btn(id,'work-rack',id,t.stage===1&&id===t.order?'primary':'')).join('')+'</div>'+(t.stage===1?'<h3>Scan & pack the manifest</h3><div class="scan-belt">'+t.items.map((id,i)=>'<button data-act="work-pack" data-id="'+id+'" '+(i!==t.packed.length?'disabled':'')+'>'+'<span class=work-product>'+U.art(C.product(id))+'</span>'+C.product(id).name+(i<t.packed.length?' ✓':'')+'</button>').join('')+'</div>'+(w.role!=='pickup'?'<p>Secure packing / load points: '+t.secured+'/3</p><div class="row">'+[0,1,2].map(i=>btn(i<t.secured?'Secured':'Secure point '+(i+1),'work-secure',i)).join('')+'</div>':'')+'<label>Customer / destination verification code<input id="pickupCode" inputmode="numeric" maxlength="4"></label><label><input id="packageLabel" type="checkbox"> Attach the verified '+t.customer+' / '+t.order+' label</label>'+btn(w.role==='pickup'?'Release verified pickup':'Stage verified shipment','work-verify','','primary'):'');
 html+='<hr><div class="row">'+btn('Read task instructions','work-read',w.role)+btn('Break / employee center','employee')+'</div>';U.modal(role.name,html);
}
Object.assign(U.handlers,{'jobs':jobs,'employee':center,'applications':applications,'job-apply':apply,'training':training,'practice-start':role=>start(role,true),'clock-in':role=>start(role,false),'work-resume':draw,
 'job-submit':role=>{const availability=document.getElementById('jobAvailability').value.trim(),skills=document.getElementById('jobSkills').value.trim(),why=document.getElementById('jobWhy').value.trim();if(!availability||!skills||!why)throw Error('Complete the three application fields.');U.change(r=>{r.applications=r.applications||[];if(r.applications.some(a=>a.employer==='Home & Beyond'&&a.role===role&&!/declined/i.test(a.status)))throw Error('You already have an application for this role. Check its status.');r.applications.push({id:K.uid(),employer:'Home & Beyond',job:C.roles.find(x=>x.id===role).name,role,name:U.captured,resident:U.captured,availability,skills,why,status:'Ready for Miss Kayla review',date:new Date().toISOString()});});applications();},
 'interview-save':id=>{const text=document.getElementById('interview-'+id).value.trim();if(!text)throw Error('Write your interview response.');U.change(r=>{let a=r.applications.find(x=>x.id===id);a.interview=text;a.status='Interview completed — Miss Kayla review';});applications();},
 'work-read':role=>{if(!('speechSynthesis'in window))return U.toast(instructions[role]);speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(instructions[role]));},
 'work-stop':()=>{U.change(r=>r.life.work.closed=true);center();},'work-next':()=>{U.change(r=>W.next(r));draw();},
 'work-scan':i=>attempt('scan',i),'work-tender':()=>attempt('tender',document.getElementById('cashReceived').value),'work-change':v=>attempt('change',Number(v)),'work-receipt':()=>attempt('receipt',document.getElementById('customerClosing').value),
 'work-select':id=>attempt('select',id),'work-recommend':()=>attempt('recommend',document.getElementById('recommendation').value),'work-shelf':id=>attempt('shelf',id),'work-face':i=>{if(Number(i)!==U.state().l.work.task.faced)return U.toast('Face the next product.');attempt('face');},'work-stock-finish':()=>attempt('stock-finish',document.getElementById('stockQuantity').value),
 'work-service':()=>attempt('service',{message:document.getElementById('serviceResponse').value,decision:document.getElementById('returnDecision').value,amount:document.getElementById('refundAmount').value}),
 'work-rack':id=>attempt('rack',id),'work-pack':id=>attempt('pack',id),'work-secure':i=>{if(Number(i)!==U.state().l.work.task.secured)return U.toast('Secure the next point.');attempt('secure');},'work-verify':()=>attempt('verify',{code:document.getElementById('pickupCode').value,label:document.getElementById('packageLabel').checked}),
 'work-pay':()=>{const report=U.change((r,w)=>{const report=W.pay(r,{name:U.captured});w.employeeShiftReports=w.employeeShiftReports||[];w.employeeShiftReports.push(report);return report;});visible=false;U.modal('Shift recorded & paid','<p>'+report.tasks+' verified tasks · '+report.hours+' simulated hours</p><h3>Gross pay: '+cash(report.grossPay)+'</h3><p>Deposited in your existing Transition Town checking account. Your report is saved for Miss Kayla.</p>'+btn('Employee center','employee','','primary'));}
});
window.TTLifeWork={tick(seconds){if(!visible||!document.getElementById('lifeDialog').open||!document.getElementById('workProgress'))return;U.change(r=>{let w=r.life.work;if(w&&!w.closed&&!w.training)w.elapsed+=Math.min(30,seconds);});const w=U.state().l.work;if(w&&document.getElementById('workProgress'))document.getElementById('workProgress').textContent=(w.training?'Training':'On the clock')+' · '+w.done+' tasks verified · '+Math.floor(w.elapsed)+' / 300 active seconds';}};
})();
