(function(root){'use strict';const C=typeof module!=='undefined'?require('./catalog.js'):root.TTLifeCatalog,K=typeof module!=='undefined'?require('./core.js'):root.TTLifeCore;
const pick=a=>a[Math.floor(Math.random()*a.length)];
function task(role){const t={id:K.uid(),role,stage:0,scanned:[],complete:false};
 if(role==='cashier'){t.items=Array.from({length:3},()=>pick(C.products.filter(p=>p.price<30)).id);t.total=K.money(t.items.reduce((s,id)=>s+C.product(id).price,0));t.tender=Math.ceil(t.total/20)*20;t.change=0;}
 if(role==='sales'||role==='furniture'){Object.assign(t,pick(role==='sales'?[{customer:'Jordan',need:'I just moved in. I need a mattress, sheets, pillow and blanket. I have $500.',tags:['mattress','sheets','pillow','blanket'],budget:500},{customer:'Sam',need:'I have $65 for a frying pan, plate, bowl, cup and silverware.',tags:['pan','plate','bowl','cup','silverware'],budget:65}]:[{customer:'Avery',need:'I have $380 for a couch and coffee table in my small apartment.',tags:['couch','coffee-table'],budget:380},{customer:'Morgan',need:'I need a dining table and chairs. My limit is $250.',tags:['table','dining-chair'],budget:250}]));t.selected=[];}
 if(role==='stock'){t.product=pick(C.products).id;t.quantity=3+Math.floor(Math.random()*4);t.faced=0;}
 if(role==='service'){t.product=pick(C.products.filter(p=>p.price<100)).id;t.days=pick([8,12,35,42]);t.reason=pick(['I bought the wrong size.','I want to exchange this for a different style.']);}
 if(['pickup','warehouse','delivery'].includes(role)){t.customer=pick(['Jordan Lee','Avery Brooks','Morgan Green']);t.code=String(Math.floor(1000+Math.random()*9000));t.items=Array.from({length:2},()=>pick(C.products.filter(p=>role==='delivery'?p.large:!p.large)).id);t.order='HB-'+Math.floor(100+Math.random()*899);t.rack=[t.order,'HB-'+Math.floor(1000+Math.random()*900),'HB-'+Math.floor(2000+Math.random()*900)].sort(()=>Math.random()-.5);t.packed=[];t.secured=0;}
 return t;
}
function start(r,role,training){const l=K.init(r);if(!C.roles.some(x=>x.id===role))throw Error('Choose an available role.');if(l.work&&!l.work.closed)throw Error('Resume or end your current practice / shift first.');if(!training){const e=r.employment?.homeBeyond;if(!e?.active||e.role!==role)throw Error('You must be hired for this role before clocking in.');if(!l.training[role])throw Error('Finish interactive training for this role first.');}l.work={id:K.uid(),role,training,elapsed:0,done:0,mistakes:0,closed:false,task:task(role),started:new Date().toISOString(),completedTasks:[]};return l.work;}
function input(r,action,data){const work=K.init(r).work;if(!work||work.closed)throw Error('Clock in or start training.');const t=work.task;if(t.complete)throw Error('This task is already complete.');const error=text=>{work.mistakes++;throw Error(text);};
 if(action==='scan'){let i=Number(data);if(i!==t.scanned.length||i>=t.items.length)return error('Scan the next unscanned item.');t.scanned.push(t.items[i]);return;}
 if(action==='tender'){if(t.scanned.length!==t.items.length)return error('Scan every item first.');if(K.money(data)!==t.tender)return error('Enter the amount the customer handed you.');t.stage=1;return;}
 if(action==='change'){if(t.stage!==1)return error('Record the cash received first.');if(![20,10,5,1,.25,.1,.05,.01,-1].includes(Number(data)))return error('Use the cash drawer.');t.change=data===-1?0:K.money(t.change+Number(data));return;}
 if(action==='receipt'){if(t.stage!==1||t.change!==K.money(t.tender-t.total))return error('Check the change due before giving the receipt.');if(String(data).trim().length<8)return error('Add a polite customer-service closing.');t.complete=true;}
 if(action==='select'){if(t.selected.includes(data))t.selected=t.selected.filter(x=>x!==data);else if(C.product(data))t.selected.push(data);return;}
 if(action==='recommend'){let ps=t.selected.map(C.product),cost=K.money(ps.reduce((s,p)=>s+p.price,0));if(cost>t.budget)return error('This exceeds the customer’s budget. Adjust your selection.');if(!t.tags.every(tag=>ps.some(p=>p.tags.includes(tag))))return error('The customer still needs an essential item.');if(String(data).trim().length<15)return error('Explain how these products meet the customer’s needs and budget.');t.complete=true;}
 if(action==='shelf'){if(data!==C.product(t.product).dept)return error('Check the product and choose its correct department.');t.stage=1;return;}
 if(action==='face'){if(t.stage!==1)return error('Place the shipment on the correct shelf first.');t.faced=Math.min(3,t.faced+1);return;}
 if(action==='stock-finish'){if(t.faced<3)return error('Face all three shelf positions first.');if(Number(data)!==t.quantity)return error('Count the shipment units and record the correct stock quantity.');t.complete=true;}
 if(action==='service'){if(String(data.message).trim().length<15)return error('Write a professional response that explains the next step.');if(data.decision!==(t.days<=30?'refund':'manager'))return error('Check the 30-day return policy. Late returns need manager review.');if(data.decision==='refund'&&K.money(data.amount)!==C.product(t.product).price)return error('Use the original receipt price for the refund.');t.complete=true;}
 if(action==='rack'){if(data!==t.order)return error('Match the customer’s order number to the rack label.');t.stage=1;return;}
 if(action==='pack'){if(t.stage!==1)return error('Locate the correct order first.');if(data!==t.items[t.packed.length])return error('Scan and pack the next item on the manifest.');t.packed.push(data);return;}
 if(action==='secure'){if(t.packed.length!==t.items.length)return error('Pack the merchandise first.');t.secured=Math.min(3,t.secured+1);return;}
 if(action==='verify'){if(t.stage!==1||t.packed.length!==t.items.length)return error('Match and pack the whole order first.');if(String(data.code)!==t.code)return error('Verify the customer’s four-digit pickup code.');if(t.role!=='pickup'&&t.secured<3)return error('Secure all three points on the package / load.');if(!data.label)return error('Attach the verified customer / destination label.');t.complete=true;}
 if(t.complete){work.done++;work.completedTasks.push(t.id);if(work.training&&work.done>=3)r.life.training[work.role]=true;}
}
function next(r){const w=K.init(r).work;if(!w?.task.complete)throw Error('Finish the current work task first.');w.task=task(w.role);}
function pay(r,world){const w=K.init(r).work;if(!w||w.closed||w.training)throw Error('This is not an unpaid active work shift.');const e=r.employment?.homeBeyond;if(!e?.active||e.role!==w.role)throw Error('Your job assignment changed. Ask Miss Kayla to review the shift.');if(w.elapsed<300||w.done<6)throw Error('Finish at least 6 verified tasks and 5 active real minutes before clocking out for pay.');const wage=C.roles.find(x=>x.id===w.role).wage,gross=K.money(wage*8);r.checking=K.money(Number(r.checking)+gross);w.closed=true;w.grossPay=gross;K.log(r,gross,'Home & Beyond verified '+w.role+' shift');const report={id:w.id,employee:world.name,employer:'Home & Beyond',position:C.roles.find(x=>x.id===w.role).name,hours:8,grossPay:gross,tasks:w.done,mistakes:w.mistakes,activeSeconds:w.elapsed,date:new Date().toISOString()};e.shifts=e.shifts||[];e.shifts.push(report);return report;}
const api={task,start,input,next,pay};if(typeof module!=='undefined')module.exports=api;else root.TTLifeWorkCore=api;
})(typeof window!=='undefined'?window:globalThis);
