'use strict';
const C=CoffeeShop,M=C.menu,app=document.getElementById('app'),coffeeOwner=C.name();
let build={drink:null,size:null,temp:null,milk:'Whole',flavors:{},shots:2,sweetener:'None',ice:'Regular Ice',toppings:[],food:'None',extras:[]},activeId=Number(localStorage.ttCoffeeActiveOrder||0),sip=100,foodLeft=4,problem=null;
const IMG={counter:'coffee-01-customer-counter.png',waiting:'coffee-03-customer-waiting-table.png'};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function scene(file,alt,overlay=''){return `<div class="scene"><img src="${file}" alt="${alt}" onerror="this.hidden=true;this.parentElement.classList.add('missing')"><div class="assetMissing"><b>Approved Coffee Shop scene asset</b><small>This page is wired for ${esc(file)}.</small></div>${overlay}</div>`}
function isKayla(){return /kayla/i.test(C.name())}
function employment(){let w=C.world(),r=C.resident(w);return r&&r.employment&&r.employment.coffee||null}
function syncEmp(){let b=document.getElementById('empBtn');if(!b)return;b.textContent=isKayla()||employment()?'Employee Entrance':'Apply Now';b.onclick=()=>location.href='coffee-employee.html'+(isKayla()?'?manager=1':'')}
function choices(vals,key){return `<div class="grid">${vals.map(v=>`<button class="choice ${build[key]===v?'on':''}" onclick="setB('${key}','${String(v).replace(/'/g,"\\'")}')">${esc(v)}</button>`).join('')}</div>`}
function setB(k,v){build[k]=v;if(k==='drink'){if(/Iced|Cold Brew|Refresher|Frappé/.test(v))build.temp='Iced';else if(!build.temp)build.temp='Hot'}renderOrder()}
function toggleTop(v){let i=build.toppings.indexOf(v);i>=0?build.toppings.splice(i,1):build.toppings.push(v);renderOrder()}
function flavor(v,amt){if(amt==='No')delete build.flavors[v];else build.flavors[v]=amt;renderOrder()}
function renderOrder(){
 app.innerHTML=scene(IMG.counter,'Approved Coffee Shop customer counter')+`<section class="card"><h1>What can I get started for you?</h1><h3>DRINK</h3>${choices(M.drinks,'drink')}<h3>SIZE</h3>${choices(M.sizes,'size')}<h3>HOT / ICED</h3>${choices(M.temps,'temp')}<h3>MILK</h3>${choices(M.milks,'milk')}<h3>FLAVOR + MODIFIER</h3><div class="mods">${M.flavors.filter(x=>x!=='None').map(f=>{let cv=build.flavors[f]||'No';return `<label>${f}<select onchange="flavor('${f}',this.value)">${['No','Light','Regular','Extra','Add'].map(v=>`<option ${v===cv?'selected':''}>${v}</option>`).join('')}</select></label>`}).join('')}</div><h3>ESPRESSO SHOTS</h3><div class="grid">${[0,1,2,3,4].map(n=>`<button class="choice ${build.shots===n?'on':''}" onclick="build.shots=${n};renderOrder()">${n}</button>`).join('')}</div><h3>SWEETENER</h3>${choices(M.sweeteners,'sweetener')}<h3>ICE</h3>${choices(M.ice,'ice')}<h3>TOPPINGS / EXTRAS</h3><div class="grid">${M.toppings.map(v=>`<button class="choice ${build.toppings.includes(v)?'on':''}" onclick="toggleTop('${v.replace(/'/g,"\\'")}')">${v}</button>`).join('')}</div><h3>FOOD / PASTRY</h3>${choices(M.foods,'food')}<p><button class="btn primary" onclick="review()">REVIEW ORDER</button></p></section>`;
}
function summary(o){return `<b>${esc(o.size)} ${esc(o.temp)} ${esc(o.drink)}</b><br>${esc(o.milk)} milk • ${o.shots} shot(s) • ${esc(o.ice)}${Object.keys(o.flavors||{}).length?'<br>'+Object.entries(o.flavors).map(([k,v])=>esc(v+' '+k)).join(' • '):''}${(o.toppings||[]).length?'<br>'+o.toppings.map(esc).join(' • '):''}${o.food&&o.food!=='None'?'<br>Food: '+esc(o.food):''}`}
function review(){if(!build.drink||!build.size||!build.temp){alert('Choose a drink, size, and hot or iced.');return}let total=C.price(build);app.innerHTML=scene(IMG.counter,'Approved customer counter')+`<section class="card"><h1>Review Order</h1><div class="receipt">${summary(build)}<hr><b>Total: $${total.toFixed(2)}</b></div><div class="row"><button class="btn" onclick="renderOrder()">CHANGE ORDER</button><button class="btn green" onclick="pay('CARD')">PAY CARD</button><button class="btn primary" onclick="pay('CASH')">PAY CASH</button></div></section>`}
function pay(method){if(C.name()!==coffeeOwner)return alert('Your active resident changed. Reload to use your own order.');if(build.receiptId)return waiting();let total=C.price(build),w=C.world(),r=C.resident(w);if((method==='CARD'||r?.life)&&r&&Number(r.checking||0)<total){alert('Card declined: not enough money in checking.');return}if((method==='CARD'||r?.life)&&r){r.checking=Math.round((Number(r.checking||0)-total)*100)/100;C.save(w)}let o=C.addOrder({resident:C.name(),drink:JSON.parse(JSON.stringify(build)),food:build.food,total,paymentStatus:'PAID',paymentMethod:method,source:'customer-counter',barista:{made:null,accuracy:null},foodWork:{},pickup:{}});build.receiptId=o.id;activeId=o.id;localStorage.ttCoffeeActiveOrder=o.id;waiting()}
function waiting(){let o=C.getOrder(activeId);if(!o)return renderOrder();if(o.status==='READY')return readyPhone(o);app.innerHTML=scene(IMG.waiting,'Approved empty customer waiting table')+`<section class="card"><span class="status">ORDER #${o.id} • ${esc(o.status)}</span><h1>Your order is being made.</h1><p>Relax at the table. Your phone will notify you when the entire order is ready.</p>${isKayla()?'<button class="btn" onclick="managerComplete()">MANAGER TEST: COMPLETE ORDER</button>':''}</section>`;setTimeout(waiting,1800)}
function managerComplete(){let o=C.getOrder(activeId);C.patch(activeId,{drinkStatus:'READY',foodStatus:o.food&&o.food!=='None'?'READY':'NOT NEEDED'});waiting()}
function readyPhone(o){let phone=`<div class="phone"><small>TRANSITION TOWN COFFEE SHOP</small><h2>☕ Your order is ready!</h2><p>Order #${o.id}</p><button class="btn green" onclick="pickup()">PICK UP MY ORDER</button></div>`;app.innerHTML=scene(IMG.waiting,'Approved empty waiting table',phone)+'<section class="card"><h2>Your phone buzzes.</h2><p>Your order is ready at the pickup counter.</p></section>';if(navigator.vibrate)navigator.vibrate([120,80,120]);chime()}
function chime(){try{let a=new (window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=880;g.gain.value=.04;o.start();o.stop(a.currentTime+.16)}catch(e){}}
function pickup(){let o=C.getOrder(activeId);if(!o||o.resident!==C.name())return alert('Open your own order first.');if(o.status!=='READY')return waiting();const w=C.world(),r=C.resident(w),stored=w.coffeeOrders.find(x=>x.id===o.id);if(r?.life&&o.food&&o.food!=='None'&&!stored.lifePacked){stored.lifePacked=true;r.life.meals.push({id:'coffee-'+o.id,name:o.food,hunger:20});C.save(w);}C.patch(activeId,{status:'PICKED UP',pickupStatus:'PICKED UP',pickedUpAt:Date.now()});problem=Math.random()<.2?pickProblem(o):null;sip=100;foodLeft=o.food&&o.food!=='None'?4:0;table()}
function pickProblem(o){let a=['Wrong drink','Wrong size','Wrong milk','Hot instead of iced','Iced instead of hot','Missing flavor','Too much flavor','Missing topping','Spilled drink','Drink too hot','Contamination'];if(o.food&&o.food!=='None')a.push('Missing food');return a[Math.floor(Math.random()*a.length)]}
function table(){let o=C.getOrder(activeId);let issue=problem?`<div class="problem"><b>Something is wrong: ${esc(problem)}.</b><p>What should you do?</p><div class="grid"><button class="choice" onclick="handleProblem('ignore')">IGNORE IT</button><button class="choice" onclick="handleProblem('counter')">TAKE IT BACK</button></div></div>`:'';app.innerHTML=scene(IMG.waiting,'Approved customer table after pickup')+`<section class="card"><h1>Order #${o.id}</h1><div class="eatDrink"><div class="straw"></div><div class="liquid" style="height:${sip}%"></div></div><div class="food">${foodLeft?'🥐':''}</div>${issue}<div class="grid"><button class="choice" onclick="sipDrink()">TAKE A SIP</button>${foodLeft?'<button class="choice" onclick="eatFood()">EAT FOOD</button>':''}<button class="choice" onclick="useNapkin()">USE NAPKIN</button><button class="choice" onclick="trash()">THROW AWAY TRASH</button></div><p id="tableMsg"></p><button class="btn green" onclick="finish()">FINISHED</button></section>`}
function sipDrink(){sip=Math.max(0,sip-20);problem=null;table()}
function eatFood(){foodLeft=Math.max(0,foodLeft-1);if(foodLeft===0){const w=C.world(),r=C.resident(w),o=C.getOrder(activeId);if(o?.resident===C.name()&&r?.life?.meals.some(m=>m.id==='coffee-'+activeId)){TTLifeCore.eat(r,'coffee-'+activeId,true);C.save(w);}}problem=null;table()}
function useNapkin(){document.getElementById('tableMsg').textContent='You use a napkin and keep your table neat.'}
function trash(){sip=0;foodLeft=0;document.getElementById('tableMsg').textContent='Trash thrown away. Thank you for cleaning your table.'}
function handleProblem(a){if(a==='ignore'){problem=null;table();return}app.innerHTML=scene(IMG.counter,'Coffee Shop counter')+`<section class="card"><h1>Speak Up Politely</h1><p>Choose what you would say.</p><div class="grid"><button class="choice" onclick="remake()">“Excuse me, there is a problem with my order. Could you please remake it?”</button><button class="choice" onclick="remake()">“This isn’t what I ordered. Could I please get the correct one?”</button></div></section>`}
function remake(){problem=null;let o=C.getOrder(activeId);C.patch(activeId,{status:'PREPARING REMAKE',drinkStatus:'WAITING'});app.innerHTML='<section class="card"><div class="status">The employee apologizes and remakes the item. Contaminated drinks are replaced, not repaired.</div><button class="btn green" onclick="managerComplete()">CONTINUE REMAKE</button></section>'}
function finish(){C.patch(activeId,{completed:true,status:'COMPLETED',completedAt:Date.now()});localStorage.removeItem('ttCoffeeActiveOrder');activeId=0;app.innerHTML='<section class="card"><h1>Thanks for visiting!</h1><div class="row"><button class="btn primary" onclick="resetOrder()">ORDER AGAIN</button><button class="btn" onclick="C.returnTown()">RETURN TO TRANSITION TOWN</button></div></section>'}
function resetOrder(){build={drink:null,size:null,temp:null,milk:'Whole',flavors:{},shots:2,sweetener:'None',ice:'Regular Ice',toppings:[],food:'None',extras:[]};renderOrder()}
syncEmp();if(activeId&&C.getOrder(activeId)?.resident===C.name()&&!C.getOrder(activeId).completed)waiting();else renderOrder();