/* Presentation only: recipe and resident state stay in their existing applications. */
(function(root){'use strict';
const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function scene({kind='eggs',step=0,complete=false,interactive=false}={}){
 const food=['eggs','toast','pasta','chicken'].includes(kind)?kind:'eggs';
 return '<section class="kitchen-scene3d" data-kind="'+food+'" data-step="'+Number(step)+'" data-complete="'+Boolean(complete)+'" data-interactive="'+Boolean(interactive)+'" aria-label="Interactive three-dimensional home kitchen"><div class="kitchen-viewport"><img class="kitchen-model-fallback" src="transition-life/assets/kitchen-3d/kitchen-3d-overview.webp" alt="Static preview of the modeled kitchen, with sage cabinets, steel appliances and a furnished cooking island"><canvas class="kitchen-canvas" role="img" aria-label="3D kitchen. Use the view buttons to inspect the room, worktop, and stove."></canvas><span id="panFood" class="kitchen-stir-signal" aria-hidden="true"></span><span class="kitchen-render-state" role="status">Opening 3D kitchen…</span></div><div class="kitchen-view-controls" role="group" aria-label="Kitchen camera views"><button type="button" data-kitchen-view="room" aria-pressed="true">Room</button><button type="button" data-kitchen-view="worktop" aria-pressed="false">Worktop</button><button type="button" data-kitchen-view="stove" aria-pressed="false">Stove</button><button type="button" data-kitchen-view="prep" aria-pressed="false">Prep area</button></div><p class="kitchen-object-hint" role="status">'+safe(interactive?'Drag around the pan to stir, or use the Stir once button.':'Drag to look around. Tap a kitchen object to inspect it.')+'</p></section>';
}
root.TTKitchenArt={scene};
if(typeof MutationObserver!=='undefined')import('./kitchen-3d.js').catch(()=>{document.querySelectorAll('.kitchen-render-state').forEach(el=>el.textContent='3D is unavailable here. Cooking controls still work.');});
})(window);
