(()=>{
 const KEY='tt_temp_session_v1';
 const areas=['Job Exploration','Workplace Readiness','Self-Advocacy','Postsecondary Counseling'];
 let timer=null;
 const now=()=>Date.now();
 const load=()=>{try{return JSON.parse(sessionStorage.getItem(KEY)||'null')}catch{return null}};
 const save=s=>sessionStorage.setItem(KEY,JSON.stringify(s));
 const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 function elapsed(s){return Math.max(0,Math.floor(((s.pausedAt||now())-s.startedAt-(s.pausedTotal||0))/1000))}
 function fmt(sec){return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
 function ensureUI(){
  if(document.getElementById('tt-sessionbar'))return;
  document.body.insertAdjacentHTML('afterbegin',`<div id="tt-sessionbar" class="tt-sessionbar"><button class="tt-start" id="tt-start">⏱ Start 30-Min Session</button><span class="tt-pill" id="tt-label">No active session</span><span class="tt-pill" id="tt-time">00:00 / 30:00</span><button class="tt-start" id="tt-pause" hidden>Pause</button><button class="tt-end" id="tt-finish" hidden>Finish & Data Box</button></div><div class="tt-modal" id="tt-modal" role="dialog" aria-modal="true"><div class="tt-dialog" id="tt-dialog"></div></div>`);
  document.getElementById('tt-start').addEventListener('click',startDialog);document.getElementById('tt-pause').addEventListener('click',togglePause);document.getElementById('tt-finish').addEventListener('click',finishDialog);
  document.getElementById('tt-modal').addEventListener('click',e=>{if(e.target.id==='tt-modal')closeModal()});
 }
 function openModal(html){document.getElementById('tt-dialog').innerHTML=html;document.getElementById('tt-modal').classList.add('open')}
 function closeModal(){document.getElementById('tt-modal').classList.remove('open')}
 function startDialog(){openModal(`<h2>Start a 30-Minute Session</h2><p>This label is temporary and stays only in this browser tab until you clear the session.</p><div class="tt-field"><label for="tt-name"><b>Temporary student label</b> (first name, initials, or Student 1)</label><input id="tt-name" maxlength="40" placeholder="Example: J., Student 1"></div><div class="tt-actions"><button class="tt-primary" id="tt-go">Start Session</button><button class="tt-secondary" id="tt-cancel">Cancel</button></div>`);document.getElementById('tt-go').onclick=()=>{const label=document.getElementById('tt-name').value.trim()||'Student';save({label,startedAt:now(),pausedTotal:0,pausedAt:null,activities:[],choices:[]});closeModal();track('Session started');render()};document.getElementById('tt-cancel').onclick=closeModal}
 function togglePause(){let s=load();if(!s)return;if(s.pausedAt){s.pausedTotal+=(now()-s.pausedAt);s.pausedAt=null}else{s.pausedAt=now()}save(s);render()}
 function track(activity,detail=''){let s=load();if(!s)return;s.activities=s.activities||[];if(!s.activities.some(x=>x.activity===activity))s.activities.push({activity,detail,at:elapsed(s)});save(s)}
 function choice(label,value){let s=load();if(!s)return;s.choices=s.choices||[];s.choices.push({label,value,at:elapsed(s)});save(s)}
 function render(){let s=load(),lab=document.getElementById('tt-label'),t=document.getElementById('tt-time'),p=document.getElementById('tt-pause'),f=document.getElementById('tt-finish'),st=document.getElementById('tt-start');if(!s){lab.textContent='No active session';t.textContent='00:00 / 30:00';p.hidden=f.hidden=false;p.hidden=true;f.hidden=true;st.hidden=false;return}st.hidden=true;p.hidden=f.hidden=false;lab.textContent=`Current: ${s.label}`;const e=elapsed(s);t.textContent=`${fmt(e)} / 30:00`;p.textContent=s.pausedAt?'Resume':'Pause';if(e>=1800)t.textContent=`✓ ${fmt(e)} — Session complete`}
 function summaryFor(area,s){const acts=(s.activities||[]).filter(x=>x.activity!=='Session started').map(x=>x.activity);const unique=[...new Set(acts)];const list=unique.slice(0,5).join(', ')||'guided transition activities';const map={
 'Job Exploration':`Student participated in a 30-minute job exploration session using ${list}. Student explored career duties, workplace expectations, skills, and real-life job situations through interactive activities and discussion. Student practiced making career-related decisions and identifying personal interests. Next session will continue career exploration and comparison of related employment options.`,
 'Workplace Readiness':`Student participated in a 30-minute workplace readiness session using ${list}. Student practiced workplace communication, following directions, problem-solving, responsibility, and responding to realistic job situations. Student reviewed how choices involving attendance, coworkers, supervisors, customers, and assigned tasks can affect employment. Next session will continue workplace readiness through real-life employment scenarios.`,
 'Self-Advocacy':`Student participated in a 30-minute self-advocacy session using ${list}. Student practiced expressing needs, asking for help or clarification, making choices, communicating appropriately, and responding to challenging real-life situations. Student reviewed when and how to seek support while increasing independent decision-making. Next session will continue self-advocacy through guided real-life scenarios.`,
 'Postsecondary Counseling':`Student participated in a 30-minute postsecondary counseling session using ${list}. Student explored education and training options connected to future career goals and practiced comparing pathways, requirements, and next steps after high school. Student discussed how career interests can connect to college, technical training, credentials, or employment. Next session will continue postsecondary planning and pathway exploration.`};return map[area]}
 function finishDialog(){let s=load();if(!s)return startDialog();const dur=fmt(elapsed(s));openModal(`<h2>Session Complete</h2><p><b>${esc(s.label)}</b> • ${dur}</p><p>Choose the one Pre-ETS area for this data box:</p><div class="tt-area-grid" id="tt-areas">${areas.map(a=>`<button data-area="${a}">${a}</button>`).join('')}</div><div id="tt-output"></div><div class="tt-actions"><button class="tt-danger" id="tt-clear">End & Clear Session</button><button class="tt-secondary" id="tt-close">Keep Session Open</button></div>`);document.querySelectorAll('#tt-areas button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#tt-areas button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const text=summaryFor(b.dataset.area,s);document.getElementById('tt-output').innerHTML=`<h3>Screenshot-Ready Data Box</h3><div class="tt-result"><b>${esc(b.dataset.area)}</b><br><span id="tt-data-text">${esc(text)}</span></div><div class="tt-actions"><button class="tt-primary" id="tt-copy">Copy Data Box</button><button class="tt-secondary" id="tt-hide">Hide Student Label</button><button class="tt-secondary" id="tt-print">Print</button></div>`;document.getElementById('tt-copy').onclick=async()=>{try{await navigator.clipboard.writeText(text);document.getElementById('tt-copy').textContent='Copied ✓'}catch{document.getElementById('tt-copy').textContent='Select text to copy'}};document.getElementById('tt-hide').onclick=()=>{document.querySelector('#tt-dialog>p').innerHTML=`<b>Student label hidden</b> • ${dur}`};document.getElementById('tt-print').onclick=()=>window.print()});document.getElementById('tt-clear').onclick=()=>{sessionStorage.removeItem(KEY);closeModal();render()};document.getElementById('tt-close').onclick=closeModal}
 function speak(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.95;window.speechSynthesis.speak(u)}
 window.TT={track,choice,speak,finish:finishDialog};
 ensureUI();render();timer=setInterval(render,1000);document.addEventListener('click',e=>{const a=e.target.closest('[data-tt-activity]');if(a)track(a.dataset.ttActivity);const sp=e.target.closest('[data-speak]');if(sp)speak(sp.dataset.speak)});
})();
