// Browser UI + two independent clients using a deterministic in-memory room transport.
// This tests game integration; it does not certify the external Supabase service.
const {chromium}=require('playwright'),http=require('http'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const mock=`export function createClient(){return {channel(name,options){const listeners=[];let presence={},cb;window.__deliver=msg=>{if(msg.kind==='presence'){presence=msg.state;listeners.filter(l=>l.type==='presence').forEach(l=>l.fn());}else listeners.filter(l=>l.type==='broadcast'&&l.event===msg.event).forEach(l=>l.fn({payload:msg.payload}));};const c={on(type,filter,fn){listeners.push({type,event:filter.event,fn});return c;},subscribe(fn){cb=fn;queueMicrotask(()=>fn('SUBSCRIBED'));return c;},track(data){return window.__net({kind:'track',name,key:options.config.presence.key,data});},presenceState(){return presence;},send(data){return window.__net({kind:'send',name,...data});},untrack(){return window.__net({kind:'untrack',name});}};return c;},removeChannel(){}}}`;
const server=http.createServer((req,res)=>{const name=req.url.split('?')[0];if(name==='/test'){res.setHeader('Content-Type','text/html');return res.end('<meta name="viewport" content="width=device-width,initial-scale=1"><div id="rzContent"></div><script>window.recreationSports=()=>TownSports.open("basketball")</script><script type="module" src="/park-sports.js"></script>');}if(name==='/assets/vendor/supabase-2.117.2.js'){res.setHeader('Content-Type','application/javascript');return res.end(mock);}try{let txt=fs.readFileSync(path.join(root,name));if(name==='/park-sports.js')txt+='\nwindow.__basket=()=>session;';res.setHeader('Content-Type','application/javascript');res.end(txt);}catch{res.statusCode=404;res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.BASKETBALL_BROWSER||'/tmp/driving-browser/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']});const peers=new Map(),errors=[];
async function refresh(name){const list=[...peers.entries()].filter(([,v])=>v.name===name),state=Object.fromEntries(list.map(([,v])=>[v.key,[v.data]]));await Promise.all(list.map(([p])=>p.evaluate(msg=>window.__deliver(msg),{kind:'presence',state})));}
async function client(){const context=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.exposeBinding('__net',async(_,msg)=>{if(msg.kind==='track'){peers.set(p,msg);await refresh(msg.name);}if(msg.kind==='untrack'){peers.delete(p);await refresh(msg.name);}if(msg.kind==='send')await Promise.all([...peers.entries()].filter(([q,v])=>q!==p&&v.name===msg.name).map(([q])=>q.evaluate(m=>window.__deliver(m),{kind:'broadcast',event:msg.event,payload:msg.payload})));});await p.goto('http://127.0.0.1:'+server.address().port+'/test');await p.waitForFunction(()=>window.TownSports);await p.evaluate(()=>TownSports.open('basketball'));return p;}
try{const host=await client(),guest=await client();await host.click('[data-mode="host"]');await host.waitForFunction(()=>__basket()?.connected);const code=await host.locator('#ttSportRoomCode').textContent();await guest.fill('#ttSportJoinCode',code);await guest.click('[data-mode="join"]');await guest.waitForFunction(()=>__basket()?.ready);await host.waitForFunction(()=>__basket()?.ready);
await host.click('#ttCourtView');await guest.click('#ttCourtView');const before=await host.evaluate(()=>__basket().game.basket.players[1].x);await guest.keyboard.down('ArrowLeft');await guest.waitForTimeout(300);await guest.keyboard.up('ArrowLeft');await host.waitForTimeout(180);assert(await host.evaluate(()=>__basket().game.basket.players[1].x)<before,'guest controls reach host');
await host.evaluate(()=>{const b=__basket().game.basket;b.players=[{x:720,y:270},{x:260,y:200}];b.owner=0;b.cool=0;Math.random=()=>0;});await host.locator('[data-court-action="primary"]').dispatchEvent('pointerdown',{pointerId:1});await host.waitForFunction(()=>__basket().game.scores[0]===2);await guest.waitForFunction(()=>__basket().game.scores[0]===2);assert.equal(await guest.locator('#ttScore1').textContent(),'2');
await host.waitForFunction(()=>__basket().game.basket.reset<=0);await host.evaluate(()=>{const b=__basket().game.basket;b.players[1]={x:230,y:270};b.players[0]={x:650,y:200};});await guest.waitForTimeout(300);await guest.locator('[data-court-action="primary"]').dispatchEvent('pointerdown',{pointerId:2});await host.waitForFunction(()=>__basket().game.scores[1]===2);await guest.waitForFunction(()=>__basket().game.scores[1]===2);
await host.click('#ttSportRestart');await guest.waitForFunction(()=>__basket().game.scores.every(n=>n===0));assert.equal(await host.evaluate(()=>__basket().game.cpu),false);
await host.screenshot({path:'/tmp/basketball-online.png'});await guest.setViewportSize({width:390,height:844});assert(await guest.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await guest.evaluate(()=>TownSports.stop());await host.waitForFunction(()=>!__basket().ready);assert.deepEqual(errors,[]);console.log('PASS: two isolated clients join, guest movement/shooting, shared score, restart, disconnect and mobile width');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
