/* Run with Playwright installed. Browser path can be supplied with DRIVING_BROWSER. */
const {chromium}=require('playwright'),http=require('http'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),mime={'.js':'application/javascript','.css':'text/css','.webp':'image/webp','.png':'image/png','.html':'text/html'};
const server=http.createServer((req,res)=>{const p=path.join(root,decodeURIComponent(req.url.split('?')[0]));try{res.setHeader('Content-Type',mime[path.extname(p)]||'text/plain');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end('missing')}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,b=await chromium.launch({executablePath:process.env.DRIVING_BROWSER||'/tmp/driving-browser/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox','--no-zygote','--single-process']});let errors=[],failed=[];const p=await b.newPage({viewport:{width:844,height:390},hasTouch:true,isMobile:true});p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)failed.push(r.url())});await p.clock.install({time:new Date('2026-10-06T12:00:00Z')});await p.goto(base+'/driving-simulator-game.html');await p.evaluate(()=>localStorage.ttCurrent='Olivia');await p.reload();await p.click('#enter');await p.clock.runFor(500);const snap=()=>p.evaluate(()=>TTDriving.snapshot());assert.equal((await snap()).state.v,0);assert.equal((await snap()).student,'Olivia');
await p.screenshot({path:'/tmp/driving-landscape.png'});
// Keyboard procedure, interlocks and observation controls.
await p.keyboard.press('Enter');assert.equal((await snap()).state.engine,false);await p.keyboard.press('b');await p.keyboard.down('ArrowDown');await p.clock.runFor(50);await p.keyboard.press('Enter');assert.ok((await snap()).state.engine);for(const k of ['2','4']){await p.keyboard.down(k);await p.clock.runFor(450);await p.keyboard.up(k);}await p.keyboard.press('r');assert.equal((await snap()).state.gear,'R');await p.keyboard.up('ArrowDown');
// Touch pedal and draggable steering wheel use DOM input handlers, not mutated physics.
const pointer=async(id,type,pointerId,x,y)=>p.evaluate(({id,type,pointerId,x,y})=>{let e=new PointerEvent(type,{pointerId,pointerType:'touch',clientX:x,clientY:y,bubbles:true});let el=document.getElementById(id);if(type==='pointerdown')el.setPointerCapture=()=>{};el.dispatchEvent(e)}, {id,type,pointerId,x,y});
let gasBox=await p.locator('#gas').boundingBox(),wheelBox=await p.locator('#wheel').boundingBox(),gasId=12,wheelId=13;
const gas=async(v)=>{await pointer('gas','pointerdown',gasId,gasBox.x+gasBox.width/2,gasBox.y+gasBox.height*v);};const gasOff=()=>pointer('gas','pointerup',gasId,0,0);
const steer=async(v)=>{await pointer('wheel','pointerup',wheelId,0,0);await pointer('wheel','pointerdown',wheelId,wheelBox.x+wheelBox.width/2,wheelBox.y+wheelBox.height/2);await pointer('wheel','pointermove',wheelId,wheelBox.x+wheelBox.width/2+v*wheelBox.width*.5,wheelBox.y+wheelBox.height/2);};
async function driveUntil(fn,controls,max=80){for(let i=0;i<max*10;i++){let s=(await snap()).state;if(fn(s))return;if(controls)await controls(s);await p.clock.runFor(100);}throw Error('Timed out: '+JSON.stringify((await snap()).state));}
const brake=async(t=700)=>{await gasOff();await pointer('wheel','pointerup',wheelId,0,0);await p.keyboard.down('ArrowDown');await p.clock.runFor(t);};
await gas(.14);await driveUntil(s=>s.x>-2.1);await steer(-1);await driveUntil(s=>s.yaw>-.03);await brake();assert.ok((await snap()).state.x>0);assert.equal((await snap()).state.v,0);await p.keyboard.press('d');for(const k of ['1','3']){await p.keyboard.down(k);await p.clock.runFor(450);await p.keyboard.up(k);}await p.keyboard.up('ArrowDown');
await driveUntil(s=>s.z>67,async s=>{await gas(s.z<62?.33:.14);await steer(Math.max(-.4,Math.min(.4,(3-s.x)*.4-s.yaw*2)));});await brake(1800);assert.ok((await snap()).events.some(e=>e.text.includes('Stop sign: complete stop')));
// Pedestrian crosses independently; the student stays stopped rather than answering a question.
await p.clock.runFor(15000);for(const k of ['1','3']){await p.keyboard.down(k);await p.clock.runFor(450);await p.keyboard.up(k);}await p.keyboard.press('e');await p.keyboard.up('ArrowDown');await gas(.14);await steer(0);await driveUntil(s=>s.z>71);await steer(.79);await driveUntil(s=>s.yaw>Math.PI/2-.02);await steer(0);await p.clock.runFor(500);
await driveUntil(s=>s.x>77,async s=>{await gas(s.x<71?.3:.14);await steer(Math.max(-.5,Math.min(.5,-(77-s.z)*.35+(Math.PI/2-s.yaw)*2)));});await p.keyboard.press('e');await steer(.72);await gas(.14);await driveUntil(s=>s.yaw>Math.PI-.03);await brake(500);await p.keyboard.up('ArrowDown');await driveUntil(s=>s.z<62.4,async s=>{let err=Math.atan2(Math.sin(s.yaw-Math.PI),Math.cos(s.yaw-Math.PI));await gas(.14);await steer(Math.max(-.4,Math.min(.4,(s.x-85)*.35-err*2)));});await brake();await p.keyboard.press('p');assert.ok((await snap()).state.finished,'destination should be physically reached');assert.equal((await snap()).events.filter(e=>/contact|collision/i.test(e.text)).length,0);await p.clock.runFor(100);assert.ok(await p.locator('#report').isVisible());assert.ok(await p.evaluate(()=>JSON.parse(localStorage.getItem('ttDrivingReports:v1')).Olivia[0].completed));await p.screenshot({path:'/tmp/driving-evaluation.png'});
// Portrait, orientation and safe-area layouts, no document overflow.
await p.setViewportSize({width:390,height:844});await p.screenshot({path:'/tmp/driving-portrait.png'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),390);await p.setViewportSize({width:844,height:390});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),844);
await p.click('#reportTown');assert.ok(p.url().includes('transition-town.html'));assert.equal(await p.evaluate(()=>localStorage.ttCurrent),'Olivia');assert.ok(await p.locator('button').filter({hasText:'Driver Training · Playable Route'}).count());
await p.keyboard.up('ArrowDown');await p.goto(base+'/driving-simulator-game.html');await p.click('#enter');await p.keyboard.down('ArrowDown');await p.keyboard.press('Enter');await p.keyboard.press('r');await p.keyboard.up('ArrowDown');await p.keyboard.down('ArrowUp');await p.clock.runFor(900);await p.keyboard.down('ArrowLeft');await p.clock.runFor(900);assert.ok((await snap()).state.yaw>-Math.PI/2+.05);await p.keyboard.up('ArrowLeft');await p.keyboard.up('ArrowUp');await p.keyboard.down('ArrowDown');await p.clock.runFor(800);assert.equal((await snap()).state.v,0);await p.keyboard.up('ArrowDown');await p.keyboard.down('ArrowRight');await p.clock.runFor(200);assert.ok((await snap()).state.steer>0);await p.keyboard.up('ArrowRight');await p.click('#pause');let frozen=(await snap()).state;await p.clock.runFor(5000);assert.deepEqual((await snap()).state,frozen);await p.click('#resume');await p.setViewportSize({width:390,height:844});await p.screenshot({path:'/tmp/driving-portrait.png'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),390);let sizes=await p.locator('.gears button, .utilities button, .pedals button, .mirror').evaluateAll(els=>els.map(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})));assert.ok(sizes.every(s=>s.w>=35&&s.h>=44));await p.setViewportSize({width:844,height:390});
console.log('PASS browser full route via touch pedals/wheel + keyboard; report/profile/return; portrait/landscape.');console.log('Runtime errors:',errors,'Failed requests:',failed);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);await b.close();server.close();})().catch(e=>{console.error(e);server.close();process.exit(1)});
