// Dependency-free integration checks. This is a DOM-shim test, not browser/layout QA.
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const C=require('../transition-life/catalog.js'),K=require('../transition-life/core.js');
function dom(){const nodes=new Map();function el(){return {style:{},children:[],attributes:{},dataset:{},listeners:{},textContent:'',_html:'',get innerHTML(){return this._html},set innerHTML(v){this._html=v;this.children=[]},appendChild(n){this.children.push(n)},setAttribute(k,v){this.attributes[k]=v},addEventListener(k,v){this.listeners[k]=v},insertAdjacentHTML(_,v){this._html+=v},focus(){this.focused=true},showModal(){this.open=true},close(){this.open=false},setPointerCapture(){}}}const get=id=>{if(!nodes.has(id))nodes.set(id,el());return nodes.get(id)};return {body:{dataset:{lifePage:'home'}},getElementById:get,createElement:el,querySelector:s=>s==='#steps button'?get('steps').children.find(x=>x.onclick)||get('steps').children[0]?.children[0]:get(s),addEventListener(){}};}
function env(document){const c={document,console,URLSearchParams,location:{search:''},sessionStorage:{},performance:{now:()=>0},setInterval:()=>0,clearInterval(){},setTimeout:()=>0,clearTimeout(){},addEventListener(){},scrollTo(){}};c.window=c;vm.createContext(c);vm.runInContext(read('kitchen-scene.js'),c);return c;}
// The original seven-step lesson, incorrect-choice feedback, completion, and restart.
const d=dom(),lesson=env(d),html=read('cooking-game.html');const inline=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)][0][1];vm.runInContext(inline,lesson);assert.equal(d.getElementById('steps').children.length,7);lesson.choose(3);assert.match(d.getElementById('msg').textContent,/Try again/);assert.equal(d.getElementById('steps').children.length,7);for(let i=0;i<7;i++)lesson.choose(i);assert.match(d.getElementById('msg').textContent,/completed/);assert.equal(d.querySelector('.kitchen-progress').attributes['aria-valuenow'],7);d.getElementById('steps').children[0].children[0].onclick();assert.equal(d.getElementById('steps').children.length,7);
for(const recipe of C.recipes){
 const doc=dom(),ctx=env(doc);const r={checking:10000,savings:400,home:'Not selected',history:[],notifications:[]},other={checking:1234,savings:22,home:'Other resident'};K.init(r);K.acquire(r,{property:'Practice apartment',rent:100,deposit:100,status:'Approved'});K.utility(r,'water');K.utility(r,'electric');r.life.introSeen=true;r.life.keysPending=false;r.life.room='kitchen';r.life.cart=['pan','pot','plate','bowl','utensils'].map(id=>({id,qty:1}));K.checkout(r);r.life.food=Object.keys(recipe.ingredients).map((tag,i)=>({id:'food'+i,name:tag,tag,qty:8,raw:tag==='chicken'}));const w={residents:{A:r,B:other}};ctx.TTLifeCatalog=C;ctx.TTLifeCore=K;ctx.TTLifeStore={name:()=> 'A',read:()=>w,change:fn=>fn(r,w),sandbox:()=>false,teacher:()=>false};vm.runInContext(read('transition-life/app.js'),ctx);const ui=ctx.TTLifeUI,before=JSON.stringify(r.life.food),bank=r.checking,otherBefore=JSON.stringify(other);
 ui.handlers.stove();assert.match(doc.getElementById('dialogBody').innerHTML,/kitchen-scene3d/);ui.handlers['cook-start'](recipe.id);ui.handlers['cook-next']();ui.close();assert.equal(JSON.stringify(r.life.food),before,'cancel must not consume food');ui.handlers['cook-start'](recipe.id);ui.handlers['cook-next']();ui.handlers['cook-next']();ui.handlers['cook-next']();assert.match(doc.getElementById('lifeToast').textContent,/Stir the food first/);assert.equal(JSON.stringify(r.life.food),before);
 if(recipe.id==='eggs'){const zone=doc.getElementById('cookZone');zone.onpointerdown({clientX:0,clientY:0,pointerId:1});for(let i=1;i<=12;i++)zone.onpointermove({clientX:i*20,clientY:0});zone.onpointercancel();}else for(let i=0;i<20;i++)ui.handlers.stir();
 assert.equal(doc.getElementById('stirStatus').textContent,'Stir progress: 12 / 12');for(let i=2;i<recipe.steps.length;i++)ui.handlers['cook-next']();assert.equal(r.life.meals.length,1);for(const [tag,count]of Object.entries(recipe.ingredients))assert.equal(r.life.food.find(x=>x.tag===tag).qty,8-count);ui.handlers['cook-next']();assert.equal(r.life.meals.length,1,'repeat must not duplicate meal');assert.equal(r.checking,bank);assert.equal(JSON.stringify(other),otherBefore);assert.ok(doc.getElementById('panFood').style.rotate,'stir gives visible feedback');
}
// Shared renderer assets and dependency ordering in both app entry points.
const art=lesson.TTKitchenArt;for(const kind of ['eggs','toast','pasta','chicken']){const scene=art.scene({kind,step:2,interactive:true});assert.match(scene,/data-interactive="true"/);assert.match(scene,/<canvas/);assert.match(scene,/data-kitchen-view="stove"/);assert.equal((scene.match(/id="panFood"/g)||[]).length,1);assert.ok(fs.existsSync(path.join(root,'transition-life/assets/kitchen-3d/scene.json')));assert.match(art.scene({kind,step:6,complete:true}),/data-complete="true"/);}
for(const name of ['transition-life.html','home-beyond.html']){const s=read(name);assert.ok(s.indexOf('src="kitchen-scene.js"')<s.indexOf('src="transition-life/app.js"'));assert.match(s,/href="kitchen-scene.css"/);}
console.log('PASS: seven-step lesson, wrong choice, restart, all five recipes, stir gate/limit, pointer cancel, tap feedback, cancellation, one-time consumption, unchanged bank/profile, shared assets and script order. DOM-shim only; browser layout remains unverified.');
