/* Run with NODE_PATH pointing to Playwright, or require it from your normal install. */
const {chromium}=require('playwright'),http=require('http'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{try{const p=path.join(root,decodeURIComponent(req.url.split('?')[0]));res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end('missing');}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;const proxyUrl=process.env.HTTPS_PROXY||process.env.https_proxy;const b=await chromium.launch({proxy:proxyUrl?{server:proxyUrl,bypass:'127.0.0.1,localhost'}:undefined,executablePath:process.env.SOFTBALL_BROWSER||'/tmp/driving-browser/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox','--single-process','--no-zygote','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
let errors=[];const context=await b.newContext({viewport:{width:844,height:390},hasTouch:true,isMobile:true,ignoreHTTPSErrors:true});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')console.log('BROWSER:',m.text().slice(0,500));});await p.goto(url+'/softball-game.html');assert.equal(await p.locator('#rendererError').isVisible(),false);await p.click('#solo');await p.waitForFunction(()=>TTSoftball.snapshot().game.phase==='pitch');
// Both field and buttons remain together in landscape; no scrolling needed to swing.
const field=await p.locator('#field').boundingBox(),swing=await p.locator('[data-action="swing"]').boundingBox();assert.ok(swing.y>=field.y&&swing.y+swing.height<=field.y+field.height);await p.screenshot({path:'/tmp/softball-landscape.png'});
await p.waitForFunction(()=>{let s=TTSoftball.snapshot();return s.game.phase==='pitch'&&s.game.pitch.t>s.game.pitch.windup+s.game.pitch.duration-.08;});await p.locator('[data-action="swing"]').dispatchEvent('pointerdown',{button:0,pointerId:3,pointerType:'touch'});assert.ok(['live','foul','result'].includes((await p.evaluate(()=>TTSoftball.snapshot())).game.phase));
await p.click('#pause');let time=(await p.evaluate(()=>TTSoftball.snapshot())).game.time;await p.waitForTimeout(200);assert.equal((await p.evaluate(()=>TTSoftball.snapshot())).game.time,time);await p.click('#helpButton');assert.ok(await p.locator('#help').isVisible());await p.click('#closeHelp');await p.setViewportSize({width:390,height:844});await p.screenshot({path:'/tmp/softball-portrait.png'});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.click('#leave');assert.equal(await p.locator('#lobby').isVisible(),true);
// Real Realtime service: two isolated pages, actual room join and controls.
const q=await p.context().newPage();await q.setViewportSize({width:960,height:760});q.on('pageerror',e=>errors.push(e.message));await q.goto(url+'/softball-game.html');await p.click('#host');const code=await p.locator('#roomCode').textContent();await q.fill('#code',code);await q.click('#join');try{await p.waitForFunction(()=>TTSoftball.snapshot().ready,{},{timeout:25000});}catch(e){console.log('HOST STATUS',await p.locator('#connection').textContent(),'GUEST STATUS',await q.locator('#connection').textContent());throw e;}await q.waitForFunction(()=>TTSoftball.snapshot().ready,{},{timeout:25000});assert.equal((await q.evaluate(()=>TTSoftball.snapshot())).side,1);
await q.locator('[data-action="pitch"]').dispatchEvent('pointerdown',{button:0,pointerId:1});await p.waitForFunction(()=>TTSoftball.snapshot().game.phase==='pitch');await q.waitForFunction(()=>TTSoftball.snapshot().game.phase==='pitch');
await p.waitForFunction(()=>{const s=TTSoftball.snapshot();return s.game.phase==='pitch'&&s.game.pitch.t>s.game.pitch.windup+s.game.pitch.duration-.08;});await p.locator('[data-action="swing"]').dispatchEvent('pointerdown',{button:0,pointerId:2});await p.waitForTimeout(200);let host=await p.evaluate(()=>TTSoftball.snapshot()),guest=await q.evaluate(()=>TTSoftball.snapshot());assert.equal(host.game.phase,'live');assert.equal(guest.game.phase,'live');assert.deepEqual(host.game.scores,guest.game.scores);
const selected=guest.game.selected,fx=host.game.fielders[selected].x;await q.keyboard.down('ArrowRight');await q.waitForTimeout(700);await q.keyboard.up('ArrowRight');host=await p.evaluate(()=>TTSoftball.snapshot());assert.ok(host.game.fielders[selected].x>fx);await p.screenshot({path:'/tmp/softball-live.png'});
// Shared pause freezes the host and is reflected on the guest.
await q.click('#pause');await p.waitForFunction(()=>TTSoftball.snapshot().paused);await q.waitForFunction(()=>TTSoftball.snapshot().paused);await q.click('#leave');await p.waitForFunction(()=>!TTSoftball.snapshot().ready);
await p.goto(url+'/transition-town.html#park');await p.waitForSelector('#recreationZone');await p.locator('.rzGame').filter({hasText:'3D Softball'}).click();await p.waitForURL('**/softball-game.html?*');await p.waitForFunction(()=>!!window.TTSoftball);assert.equal(await p.locator('#rendererError').isVisible(),false);
assert.deepEqual(errors,[]);console.log('Browser checks passed: WebGL render, phone controls, swing, pause, portrait layout, actual two-client room, guest pitch and fielder movement, synchronized state and disconnect.');await b.close();server.close();})().catch(e=>{console.error(e);process.exit(1);});
