const {chromium}=require('playwright'),http=require('http'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),server=http.createServer((req,res)=>{try{const p=path.join(root,decodeURIComponent(req.url.split('?')[0]));res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.webp')?'image/webp':'text/html');res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end('missing');}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,executablePath:process.env.STORYTIME_CHROME||'/tmp/driving-browser/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await context.route('**/*',r=>r.request().url().startsWith(url)?r.continue():r.abort());await context.addInitScript(()=>{Object.defineProperty(window,'speechSynthesis',{value:undefined,configurable:true});delete window.speechSynthesis;Object.defineProperty(window,'SpeechSynthesisUtterance',{value:undefined,configurable:true});delete window.SpeechSynthesisUtterance;});const p=await context.newPage();let errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url+'/transition-town.html');await p.selectOption('#loginProfile','Guest');await p.locator('button').filter({hasText:/^Enter Transition Town$/}).click();
const open=async()=>{await p.locator('.townmap .park').click();await p.locator('.parkplay').click();await p.locator('[aria-label="Story Time"]').click();};await open();await p.locator('[data-st-action="book"][data-index="0"]').click();assert.equal(await p.locator('[data-st-action="read"]').isDisabled(),true);await p.locator('[data-st-action="start"]').click();assert.match(await p.locator('#stVoiceStatus').textContent(),/does not support/);
// Native touch scroll actually moves the reader and never turns a page.
const cdp=await context.newCDPSession(p);await p.locator('#stSpread').scrollIntoViewIfNeeded();const bounds=await p.locator('#stSpread').boundingBox();const sy=Math.min(650,bounds.y+150),sx=195;const pageBefore=await p.locator('#stCount').textContent();const scrollBefore=await p.locator('#transitionStory').evaluate(el=>el.scrollTop);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:sx,y:sy}]});for(let i=1;i<=8;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:sx-2,y:sy-i*25}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(180);assert.equal(await p.locator('#stCount').textContent(),pageBefore);assert.ok(await p.locator('#transitionStory').evaluate((el,before)=>el.scrollTop>before,scrollBefore));
// Image network failure preserves the text and all reading controls.
await context.route('**/alyssa-bakery/page-02.webp',r=>r.fulfill({status:404,body:'missing'}));await p.locator('[data-st-action="next"]').click();await p.waitForSelector('.stImageNote');assert.match(await p.locator('#stStoryText').textContent(),/morning order list/);await p.locator('[data-st-action="next"]').click();await p.locator('[data-st-action="next"]').click();assert.equal(await p.locator('#stCount').textContent(),'Page 4 of 10');
// Resume survives a full page reload, still using the existing Guest profile.
await p.reload();if(await p.locator('#loginProfile').count()){await p.selectOption('#loginProfile','Guest');await p.locator('button').filter({hasText:/^Enter Transition Town$/}).click();}await open();await p.locator('[data-st-action="book"][data-index="0"]').click();await p.locator('[data-st-action="resume"]').click();assert.equal(await p.locator('#stCount').textContent(),'Page 4 of 10');
// Optional story question never blocks completion.
for(let i=3;i<10;i++)await p.locator('[data-st-action="next"]').click();assert.equal(await p.locator('.stEnd h1').textContent(),'The End');
await p.locator('[data-st-action="shelf"]').click();await p.keyboard.press('Escape');assert.equal(await p.locator('#transitionStory').count(),0);assert.ok(await p.locator('[aria-label="Story Time"]').isVisible());assert.deepEqual(errors,[]);console.log('Passed: unavailable speech, real touch scrolling, missing image fallback, saved resume, optional choice bypass, Escape exit.');await browser.close();server.close();})().catch(e=>{console.error(e);server.close();process.exit(1)});
