const assert=require('node:assert/strict'),K=require('../transition-life/core.js'),C=require('../transition-life/catalog.js'),W=require('../transition-life/work-core.js');
const resident=checking=>({checking:checking??10000,savings:500,home:'Not selected',job:'Needs a job',history:[],notifications:[],sessions:0});
let r=resident(),untouched=resident(4321);K.init(r);assert.equal(r.checking,10000);assert.equal(r.life.inventory.length,0);assert.equal(r.life.food.length,0);assert.equal(r.life.housing,undefined);assert.throws(()=>K.utility(r,'water'),/housing/);
const app={id:'rent1',property:'Town Center Apartments',rent:800,deposit:800,status:'Approved'};K.acquire(r,app);assert.equal(r.checking,8400);assert.equal(r.life.housing.tenure,'renter');assert.equal(r.life.inventory.length,0);assert.throws(()=>K.acquire(r,app),/already/);assert.equal(r.checking,8400);
K.utility(r,'water');K.utility(r,'electric');assert.equal(r.checking,8040);assert.equal(r.utilities.waterOn,true);assert.throws(()=>K.utility(r,'electric'),/already/);assert.equal(r.checking,8040);
r.life.cart=[{id:'mattress',qty:1},{id:'pillow',qty:2},{id:'pan',qty:1},{id:'utensils',qty:1},{id:'plate',qty:1}];let order=K.checkout(r);assert.equal(r.checking,7703);assert.equal(K.has(r,'mattress'),true);assert.equal(K.has(r,'mattress',true),false);assert.equal(K.has(r,'pillow'),true);assert.equal(K.has(untouched,'mattress'),false);assert.equal(untouched.checking,4321);assert.throws(()=>K.checkout(r),/empty/);
const bed=r.life.inventory.find(x=>x.id==='mattress');assert.throws(()=>K.place(r,bed.uid,'bedroom',40,75),/not ready/);K.schedule(r,order.id,K.plusDays(r.life.date,1),'Morning');assert.throws(()=>K.receive(r,order.id),/not due/);K.action(r,'floor-night');K.receive(r,order.id);assert.throws(()=>K.place(r,bed.uid,'kitchen',40,75),/bedroom/);K.place(r,bed.uid,'bedroom',40,75);assert.ok(K.placed(r,'mattress'));assert.throws(()=>K.returnItem(r,bed.uid),/unused/);r.life.needs.energy=10;K.action(r,'night');assert.equal(r.life.needs.energy,100);
K.ingestGroceries(r,[{key:'04-0',name:'Eggs',qty:1,price:2},{key:'02-0',name:'Bread',qty:1,price:2},{key:'04-5',name:'Butter',qty:1,price:3},{key:'14-0',name:'Body Wash',qty:1,price:4}], 'receipt1');const food=JSON.stringify(r.life.food);K.ingestGroceries(r,[{key:'04-0',name:'Eggs',qty:1}], 'receipt1');assert.equal(JSON.stringify(r.life.food),food);assert.ok(K.has(r,'hygiene'));assert.ok(K.recipeAvailable(r,'eggs-toast'));const eggCount=r.life.food.find(f=>f.tag==='eggs').qty;K.cook(r,'eggs-toast');assert.equal(r.life.food.find(f=>f.tag==='eggs').qty,eggCount-1);let meal=r.life.meals[0];r.life.needs.hunger=10;K.eat(r,meal.id,true);assert.equal(r.life.needs.hunger,60);assert.throws(()=>K.eat(r,meal.id,true),/no longer/);
const bad=resident(10);K.init(bad);bad.life.cart=[{id:'tv',qty:1}];const before=JSON.stringify(bad);assert.throws(()=>K.checkout(bad),/Not enough/);assert.equal(JSON.stringify(bad),before);
const rent=r.life.bills.find(b=>b.kind==='rent');r.life.date=rent.due;assert.equal(K.stage(rent,r.life),'DUE');r.life.date=K.plusDays(rent.due,7);assert.equal(K.stage(rent,r.life),'LATE FEE');assert.equal(K.billTotal(rent,r.life),825);r.life.date=K.plusDays(rent.due,30);K.processBills(r);assert.equal(K.stage(rent,r.life),'HOUSING AT RISK');assert.equal(r.utilities.waterOn,false);assert.ok(r.life.housing);assert.throws(()=>K.action(r,'shower'),/disconnected/);assert.throws(()=>K.utility(r,'water'),/outstanding/);
// Clear all overdue water invoices, then pay the reconnection fee exactly once.
for(let i=0;i<10;i++){const b=r.life.bills.find(b=>b.kind==='water'&&!b.paid&&K.diffDays(r.life.date,b.due)>=0);if(!b)break;K.payBill(r,b.id);}let money=r.checking;K.utility(r,'water');assert.equal(r.checking,money-25);K.action(r,'shower');assert.equal(r.utilities.waterOn,true);
const owner=resident();K.init(owner);K.acquire(owner,{property:'house-01',tenure:'owner',status:'Approved',price:150000,down:5000,financing:'Mortgage financing'});assert.equal(owner.checking,5000);assert.equal(owner.life.housing.principal,145000);assert.equal(owner.life.housing.monthly,869.35);const mortgage=owner.life.bills[0];owner.life.date=K.plusDays(mortgage.due,90);assert.equal(K.stage(mortgage,owner.life),'FORECLOSURE RISK');assert.ok(owner.life.housing);assert.ok(!K.stage(mortgage,owner.life).includes('EVICTION'));
const legacy=resident(0);legacy.home='Old apartment • $400/month';K.init(legacy);assert.equal(legacy.checking,0);assert.equal(legacy.life.housing.monthly,400);assert.equal(legacy.life.bills.length,1);K.init(legacy);assert.equal(legacy.life.bills.length,1);
const needs=K.clone(r.life.needs);K.tick(r,60*60);assert.ok(needs.hunger-r.life.needs.hunger<=.81,'offline time must not drain needs');
// All eight roles require manipulating the actual task record; a skipped task cannot be paid.
function finishTask(r){const t=r.life.work.task,role=t.role;if(role==='cashier'){t.items.forEach((_,i)=>W.input(r,'scan',i));W.input(r,'tender',t.tender);let cents=Math.round((t.tender-t.total)*100);for(const value of [20,10,5,1,.25,.1,.05,.01])while(cents>=Math.round(value*100)){W.input(r,'change',value);cents-=Math.round(value*100);}W.input(r,'receipt','Thank you for shopping with us.');}if(role==='sales'||role==='furniture'){for(const tag of t.tags){if(t.selected.map(C.product).some(x=>x.tags.includes(tag)))continue;const p=C.products.filter(p=>p.tags.includes(tag)).sort((a,b)=>a.price-b.price)[0];W.input(r,'select',p.id);}W.input(r,'recommend','These essential products meet your needs and leave money in your budget.');}if(role==='stock'){W.input(r,'shelf',C.product(t.product).dept);for(let i=0;i<3;i++)W.input(r,'face');W.input(r,'stock-finish',t.quantity);}if(role==='service')W.input(r,'service',{decision:t.days<=30?'refund':'manager',amount:C.product(t.product).price,message:'Thank you. Let me check your receipt and help with the next step.'});if(['pickup','warehouse','delivery'].includes(role)){W.input(r,'rack',t.order);t.items.forEach(id=>W.input(r,'pack',id));if(role!=='pickup')for(let i=0;i<3;i++)W.input(r,'secure');W.input(r,'verify',{code:t.code,label:true});}}
for(const role of C.roles){let worker=resident();K.init(worker);assert.throws(()=>W.start(worker,role.id,false),/hired/);W.start(worker,role.id,true);for(let i=0;i<3;i++){finishTask(worker);if(i<2)W.next(worker);}assert.equal(worker.life.training[role.id],true);assert.equal(worker.checking,10000);worker.life.work.closed=true;worker.employment={homeBeyond:{active:true,role:role.id,shifts:[]}};W.start(worker,role.id,false);assert.throws(()=>W.pay(worker,{name:'Worker'}),/6 verified/);for(let i=0;i<6;i++){finishTask(worker);if(i<5)W.next(worker);}assert.throws(()=>W.pay(worker,{name:'Worker'}),/5 active/);worker.life.work.elapsed=300;const report=W.pay(worker,{name:'Worker'});assert.equal(worker.checking,10000+role.wage*8);assert.equal(report.tasks,6);assert.throws(()=>W.pay(worker,{name:'Worker'}),/unpaid active/);}
console.log('PASS: one balance; housing gates; empty homes; profile isolation; inventory and grocery idempotency; delivery and room constraints; cooking; utilities, bills and owner protections; migration; gentle needs; eight interactive jobs and exactly-once payroll.');
