(function(){'use strict';
const $=id=>document.getElementById(id),keys=new Set(),pointers={brake:new Set(),gas:new Map()},steering={value:0,id:null,start:0,base:0};
let student='Guest',storageAvailable=true;try{student=localStorage.getItem('ttCurrent')||sessionStorage.getItem('ttCurrent')||'Guest'}catch(e){storageAvailable=false;}
let lesson=new TTDrivingCore.Lesson(student),renderer=new TTDrivingRenderer($('world')),started=false,lastTime=0,accumulator=0,mirrorClock=0,toastUntil=0,savedReport=null,guidedPractice=true,hintsUsed=false,helpWasRunning=false;
const returnLink='transition-town.html?return=1&resident='+encodeURIComponent(student);$('back').href=returnLink;$('reportTown').href=returnLink;$('studentLine').textContent='Driver: '+student;$('identity').textContent=student+' · Behind the Wheel';
const input=()=>({brake:keys.has('ArrowDown')||pointers.brake.size?1:0,throttle:keys.has('ArrowUp')?1:Math.max(0,...pointers.gas.values()),steer:keys.has('ArrowLeft')?-1:keys.has('ArrowRight')?1:steering.value});
function toast(text){if(!text)return;$('toast').textContent=text;$('toast').classList.add('show');toastUntil=performance.now()+3000;}
function resetInputs(){keys.clear();pointers.brake.clear();pointers.gas.clear();steering.id=null;steering.value=0;lesson.state.brake=0;lesson.state.throttle=0;lesson.endObserve();}
function pause(){if(!started||lesson.state.finished||!$('report').hidden)return;lesson.state.paused=true;resetInputs();$('pausePanel').hidden=false;}
function resume(){if(lesson.state.finished)return;$('pausePanel').hidden=true;$('report').hidden=true;resetInputs();lesson.state.paused=false;$('game').focus();lastTime=0;accumulator=0;}
function actuate(fn){if(!started||lesson.state.paused)return;lesson.state.brake=input().brake;toast(fn());if(lesson.state.finished)showReport(true);}
function enter(guided){guidedPractice=guided;hintsUsed=guided;started=true;$('intro').hidden=true;lesson.emit(guided?'Guided practice started with optional driving hints':'Drive started without hints');resume();}
$('enter').onclick=()=>enter(true);$('enterAssessment').onclick=()=>enter(false);$('pause').onclick=pause;$('resume').onclick=resume;$('evaluation').onclick=()=>showReport(false);$('restart').onclick=()=>{lesson=new TTDrivingCore.Lesson(student);savedReport=null;resume();};
// Secondary touch pointers do not generate compatibility clicks. Handle their release
// directly so holding the brake with one finger does not disable Start or the gears.
function vehicleButton(button,action,direct=false){
 let activeTouch=null,lastTouch=-1000;
 button.onpointerdown=e=>{if(e.pointerType!=='touch')return;e.preventDefault();activeTouch=e.pointerId;button.setPointerCapture(e.pointerId);};
 button.onpointerup=e=>{if(e.pointerId!==activeTouch)return;activeTouch=null;lastTouch=performance.now();e.preventDefault();const r=button.getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom)(direct?action():actuate(action));};
 const cancel=e=>{if(activeTouch===e.pointerId)activeTouch=null;};button.onpointercancel=cancel;button.onlostpointercapture=cancel;
 button.onclick=()=>{if(performance.now()-lastTouch>650)(direct?action():actuate(action));};
}
vehicleButton($('belt'),()=>lesson.belt());vehicleButton($('start'),()=>lesson.start());
document.querySelectorAll('[data-gear]').forEach(b=>vehicleButton(b,()=>lesson.gear(b.dataset.gear)));
vehicleButton($('signalLeft'),()=>lesson.signal('left'));vehicleButton($('signalRight'),()=>lesson.signal('right'));
vehicleButton($('pause'),pause,true);vehicleButton($('help'),openHelp,true);
for(const [id,key] of [['brake','brake'],['gas','gas']]){let b=$(id);b.onpointerdown=e=>{if(lesson.state.paused)return;e.preventDefault();b.setPointerCapture(e.pointerId);if(key==='gas'){const rect=b.getBoundingClientRect();pointers.gas.set(e.pointerId,TTDrivingCore.clamp((e.clientY-rect.top)/rect.height,.14,1));}else pointers.brake.add(e.pointerId);};b.onpointermove=e=>{if(key==='gas'&&pointers.gas.has(e.pointerId)){const rect=b.getBoundingClientRect();pointers.gas.set(e.pointerId,TTDrivingCore.clamp((e.clientY-rect.top)/rect.height,.14,1));}};const up=e=>pointers[key].delete(e.pointerId);b.onpointerup=up;b.onpointercancel=up;b.onlostpointercapture=up;}
const wheel=$('wheel');wheel.onpointerdown=e=>{if(lesson.state.paused)return;e.preventDefault();wheel.setPointerCapture(e.pointerId);steering.id=e.pointerId;steering.start=e.clientX;steering.base=steering.value;};wheel.onpointermove=e=>{if(e.pointerId!==steering.id)return;steering.value=TTDrivingCore.clamp(steering.base+(e.clientX-steering.start)/(wheel.clientWidth*.5),-1,1);};const wheelUp=e=>{if(steering.id===e.pointerId){steering.id=null;steering.value=0;}};wheel.onpointerup=wheelUp;wheel.onpointercancel=wheelUp;wheel.onlostpointercapture=wheelUp;
const views=new Map();document.querySelectorAll('[data-view]').forEach(b=>{b.onpointerdown=e=>{if(lesson.state.paused)return;e.preventDefault();b.setPointerCapture(e.pointerId);views.set(e.pointerId,b.dataset.view);lesson.observe(b.dataset.view);};const up=e=>{if(views.has(e.pointerId)){views.delete(e.pointerId);lesson.endObserve();}};b.onpointerup=up;b.onpointercancel=up;b.onlostpointercapture=up;});
const keyActions={b:()=>lesson.belt(),Enter:()=>lesson.start(),p:()=>lesson.gear('P'),r:()=>lesson.gear('R'),n:()=>lesson.gear('N'),d:()=>lesson.gear('D'),q:()=>lesson.signal('left'),e:()=>lesson.signal('right')};const keyViews={'1':'left','2':'rear','3':'right','4':'shoulder'};
addEventListener('keydown',e=>{if(!started||!$('report').hidden||!$('helpPanel').hidden)return;let k=e.key.length===1?e.key.toLowerCase():e.key;if(k===' '){e.preventDefault();if(!e.repeat){lesson.state.paused?resume():pause();}return;}if(lesson.state.paused)return;if(k.startsWith('Arrow')||keyActions[k]||keyViews[k]){e.preventDefault();if(e.repeat)return;keys.add(k);if(keyActions[k])actuate(keyActions[k]);if(keyViews[k])lesson.observe(keyViews[k]);}});
addEventListener('keyup',e=>{let k=e.key.length===1?e.key.toLowerCase():e.key;keys.delete(k);if(keyViews[k])lesson.endObserve();});
addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
function resize(){const box=$('game').getBoundingClientRect(),scale=Math.min(1.25,devicePixelRatio||1,1280/box.width);$('world').width=Math.round(box.width*scale);$('world').height=Math.round(box.height*scale);for(const id of ['rearMirror','leftMirror','rightMirror']){const b=$(id).parentElement.getBoundingClientRect();$(id).width=Math.max(100,Math.round(b.width));$(id).height=Math.max(55,Math.round(b.height));}renderer.draw(lesson);renderer.mirrors(lesson);}
addEventListener('resize',resize);resize();renderer.assets.then(results=>{if(results.includes(false))toast('Some building artwork could not load. Refresh when connected to view the approved scenes.');renderer.draw(lesson);});
// Stable fixed simulation steps; no background catch-up or frame-dependent movement.
function frame(now){if(!lastTime)lastTime=now;let elapsed=Math.min(.1,(now-lastTime)/1000);lastTime=now;if(!lesson.state.paused){accumulator+=elapsed;while(accumulator>=1/60){lesson.tick(1/60,input());accumulator-=1/60;}if(lesson.state.finished)showReport(true);}else accumulator=0;
if(!lesson.state.paused)renderer.draw(lesson);mirrorClock+=elapsed;if(mirrorClock>.1&&!lesson.state.paused){renderer.mirrors(lesson);renderer.map(lesson);mirrorClock=0;}hud();if(now>toastUntil)$('toast').classList.remove('show');requestAnimationFrame(frame);}
function hud(){updateCoach();let s=lesson.state;$('speed').textContent=Math.round(Math.abs(s.v)*2.237);$('gearDisplay').textContent=s.gear;$('beltLamp').textContent=s.belt?'BELTED':'BELT';$('beltLamp').classList.toggle('safe',s.belt);$('engineLamp').textContent=s.engine?'ENGINE ON':'ENGINE OFF';$('engineLamp').classList.toggle('safe',s.engine);$('belt').classList.toggle('active',s.belt);$('belt').setAttribute('aria-pressed',s.belt);$('start').classList.toggle('active',s.engine);$('start').textContent=s.engine?'Engine ON':'Start';$('brake').querySelector('span').textContent=input().brake?'BRAKE HELD':'BRAKE';$('wheel').style.transform='rotate('+(s.steer*120)+'deg)';$('wheel').setAttribute('aria-valuenow',Math.round(s.steer*100));$('needle').setAttribute('transform','rotate('+Math.min(180,Math.abs(s.v)*2.237/40*180)+' 110 108)');for(const b of document.querySelectorAll('[data-gear]')){b.classList.toggle('active',s.gear===b.dataset.gear);b.setAttribute('aria-pressed',s.gear===b.dataset.gear);}for(const [id,side] of [['signalLeft','left'],['signalRight','right']]){$(id).classList.toggle('active',s.signal===side&&Math.floor(s.t*2)%2===0);$(id).setAttribute('aria-pressed',s.signal===side);}$('brake').classList.toggle('active',input().brake>0);$('gas').classList.toggle('active',input().throttle>0);$('viewLabel').textContent=lesson.look?({rear:'REAR VIEW',left:'LEFT VIEW',right:'RIGHT VIEW',shoulder:'LOOKING BEHIND'})[lesson.look]:'';}
const clock=t=>Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0');
function list(id,items,fallback){$(id).replaceChildren();if(!items.length)items=[{text:fallback}];for(const e of items){let li=document.createElement('li');li.textContent=e.text;$(id).appendChild(li);}}
function save(report){if(savedReport)return;try{let all=JSON.parse(localStorage.getItem('ttDrivingReports:v1')||'{}');all[student]=(all[student]||[]).concat([report]).slice(-10);localStorage.setItem('ttDrivingReports:v1',JSON.stringify(all));savedReport=report;$('saveStatus').textContent='Evaluation saved for '+student+' on this device. This practice drive does not change licensing status.';}catch(e){storageAvailable=false;$('saveStatus').textContent='Device storage is unavailable. Download the evaluation to keep a copy.';}}
function showReport(complete){lesson.state.paused=true;resetInputs();$('pausePanel').hidden=true;$('report').hidden=false;const r={...lesson.report(),trainingMode:hintsUsed?'Guided practice':'Without hints'};$('reportTitle').textContent=complete?'First drive complete.':'Your drive so far.';$('reportMeta').textContent=student+' · '+r.route+' · '+clock(r.duration)+' driving time · '+r.distance+' m · '+r.collisions.length+' collision/contact events';list('successList',r.successes,'Keep practicing to complete more safe maneuvers.');list('practiceList',r.practice,'No violations recorded during this drive.');list('eventList',r.events.map(e=>({text:clock(e.time)+' — '+e.text})),'No events.');$('reportResume').hidden=complete;if(complete)save(r);else $('saveStatus').textContent='This is a partial drive. Download the log or return to continue.';}
$('reportResume').onclick=resume;$('download').onclick=()=>{const data={...lesson.report(),trainingMode:hintsUsed?'Guided practice':'Without hints'},blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Transition-Town-Driving-'+student.replace(/[^a-z0-9]/gi,'-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('print').onclick=()=>window.print();
// Read-only event/telemetry seam for a future authenticated remote transport.
// No localStorage-based "live instructor" and no control endpoint is exposed.
window.TTDriving={snapshot:()=>({...lesson.snapshot(),trainingMode:hintsUsed?'Guided practice':'Without hints'}),report:()=>({...lesson.report(),trainingMode:hintsUsed?'Guided practice':'Without hints'}),subscribe:fn=>{const timer=setInterval(()=>fn(lesson.snapshot()),250);return ()=>clearInterval(timer);}};
let ticks=$('ticks');for(let i=0;i<=8;i++){const a=Math.PI+i*Math.PI/8,x=110+Math.cos(a)*86,y=108+Math.sin(a)*86,n=document.createElementNS('http://www.w3.org/2000/svg','text');n.setAttribute('x',x);n.setAttribute('y',y);n.setAttribute('fill','#aab7bf');n.setAttribute('font-size','8');n.setAttribute('text-anchor','middle');n.textContent=i*5;ticks.appendChild(n);}

// Instructional support is optional and never drives the vehicle or completes an action.
function openHelp(){helpWasRunning=started&&!lesson.state.paused;lesson.state.paused=true;resetInputs();$('helpPanel').hidden=false;$('closeHelp').focus();}
function closeHelp(){$('helpPanel').hidden=true;if(helpWasRunning)resume();else if(!started)$('introHelp').focus();else $('resume').focus();}
for(const id of ['help','introHelp','pauseHelp'])$(id).onclick=openHelp;$('closeHelp').onclick=closeHelp;
$('hideCoach').onclick=()=>{guidedPractice=false;updateCoach();};$('toggleCoach').onclick=()=>{guidedPractice=!guidedPractice;if(guidedPractice)hintsUsed=true;updateCoach();};
function updateCoach(){
 const s=lesson.state;const show=guidedPractice&&started&&!s.finished&&!s.paused;$('coach').hidden=!show;$('toggleCoach').textContent=guidedPractice?'Hide practice hints':'Show practice hints';if(!show)return;
 let title,text;
 if(s.stage==='parking'){
  if(!s.belt){title='Get ready · Seatbelt';text='Tap Seatbelt in the dashboard below.';}
  else if(!['rear','left','right','shoulder'].every(v=>lesson.mirrors[v]!==undefined)){title='Get ready · Check around you';text='Hold each mirror and Look behind briefly. The windshield changes to show that direction. Let go to face forward.';}
  else if(!s.engine){title='Start the car';text='Keep one finger holding BRAKE. With another finger, tap Start. Computer: hold ↓ and press Enter.';}
  else if(s.gear!=='R'){title='Select Reverse';text='Stop and keep BRAKE held, then tap R. Let go of BRAKE before gently holding the top of GAS.';}
  else if(s.x<-2.1&&Math.abs(s.yaw+Math.PI/2)<.3){title='Back away from the school';text='Keep the wheel straight. Gently hold the top of GAS. Watch the yellow map arrow back toward the road. Release GAS and hold BRAKE whenever you need to stop.';}
  else if(s.yaw<-.15){title='Turn while backing';text='While backing slowly, drag the wheel LEFT. Watch the yellow arrow on the map turn UP the road. Hold GAS with one finger and steer with another.';}
  else{title='Stop, then select Drive';text='Release GAS and hold BRAKE until speed is 0. Keep BRAKE held and tap D. Check the side mirrors, then let go of BRAKE to drive forward.';}
 }else if(s.stage==='road'||s.stage==='approach'){
  if(s.z<58){title='Drive up Town Avenue';text='Hold the top of GAS gently and drag the wheel sideways to steer. Follow the yellow dotted map route. Keep right and stay at or below 15 MPH.';}
  else if(!lesson.stopOK){title='Stop before the intersection';text='Release GAS and hold BRAKE. Stop BEFORE the white line and crosswalk. Keep the car stopped for the pedestrian.';}
  else if(lesson.ped.active){title='Wait for the pedestrian';text='Keep BRAKE held until the person has cleared the crosswalk. Hold both side mirrors to check traffic.';}
  else{title='Prepare to turn right';text='Check left and right. Tap ▶ for the right signal. Release BRAKE, gently move forward, then steer RIGHT onto the cross street.';}
 }else if(s.stage==='intersection'){title='Turn right onto the cross street';text='When the pedestrian has cleared your path, use gentle GAS and steer RIGHT. Straighten the wheel as the yellow map arrow points right.';}
 else if(s.stage==='destination'&&s.x<72){title='Head toward Grocery';text='Follow the dotted map route along the cross street. The green parking bay is at Grocery. Steer gently and start slowing as you get close.';}
 else if(s.stage==='destination'){title='Turn into Grocery parking';text='Tap ▶ to signal right. Slow down and steer RIGHT into the parking lot. Point the yellow map arrow down toward the store.';}
 else{title='Line up in the green parking bay';text='Face the Grocery Store and use gentle GAS and small steering adjustments. Stop fully inside the green bay, hold BRAKE, then tap P to see your report.';}
 if($('coachTitle').textContent!==title)$('coachTitle').textContent=title;if($('coachText').textContent!==text)$('coachText').textContent=text;
}

requestAnimationFrame(frame);
})();
