/* Perspective Canvas renderer: one world shared by windshield, mirrors and map. */
(function(){'use strict';
const {route}=TTDrivingCore;
class Renderer{
 constructor(canvas){this.canvas=canvas;this.mirrorBuffer=document.createElement('canvas');this.mesh=[];this.images={};this.assets=Promise.all(route.buildings.concat([{asset:'driving/school.webp'}]).filter(b=>b.asset).map(b=>new Promise(resolve=>{const img=new Image();img.onload=()=>{this.images[b.asset]=img;resolve(true)};img.onerror=()=>resolve(false);img.src=b.asset;})));this.makeWorld();}
 rect(x1,z1,x2,z2,y,color){this.mesh.push({layer:y===0?0:1,points:[[x1,y,z1],[x2,y,z1],[x2,y,z2],[x1,y,z2]],color});}
 box(x,y,z,w,h,d,color){const a=x-w/2,b=x+w/2,c=z-d/2,e=z+d/2,t=y+h;const colors=Array.isArray(color)?color:[color,'#59696b',color,'#879296'];this.mesh.push({points:[[a,y,c],[b,y,c],[b,t,c],[a,t,c]],color:colors[0]},{points:[[b,y,c],[b,y,e],[b,t,e],[b,t,c]],color:colors[1]},{points:[[b,y,e],[a,y,e],[a,t,e],[b,t,e]],color:colors[2]},{points:[[a,y,e],[a,y,c],[a,t,c],[a,t,e]],color:colors[1]},{points:[[a,t,c],[b,t,c],[b,t,e],[a,t,e]],color:colors[3]});}
 makeWorld(){
 // Ground tiles stay small so perspective and near-plane clipping remain stable.
 for(const [a,b,c,d] of route.paved)for(let x=a;x<c;x+=8)for(let z=b;z<d;z+=8)this.rect(x,z,Math.min(x+8,c),Math.min(z+8,d),0,'#4f585b');
 for(let z=-24;z<110;z+=6){if(z<70||z>89){this.rect(-.16,z,-.06,z+3,.018,'#e4be66');this.rect(.06,z,.16,z+3,.018,'#e4be66');}this.rect(-6.5,z,-6,z+6,.02,'#c8c9bb');this.rect(6,z,6.5,z+6,.02,'#c8c9bb');}
 for(let x=-40;x<109;x+=6){if(x<-7||x>7)this.rect(x,79.86,x+3,80.14,.023,'#e4be66');this.rect(x,73.5,x+6,74,.02,'#c8c9bb');this.rect(x,86,x+6,86.5,.02,'#c8c9bb');}
 for(let x=-5.5;x<6;x+=1.6)this.rect(x,72.4,x+.85,75.1,.03,'#e9e8dd');this.rect(.25,70.8,5.8,71.2,.035,'#f4eee0');
 // Training bays face the building on the west; student begins in the central bay.
 for(let z=3;z<=13;z+=3.4)this.rect(-18,z,-7,z+.10,.026,'#ededdd');this.rect(-18,3,-17.88,13.2,.026,'#ededdd');
 this.box(-32,0,7,4,5,24,['#cfb889','#a08b66','#ceb989','#d8ceb0']);this.mesh.push({points:[[-29.98,0,-5],[-29.98,0,19],[-29.98,5,19],[-29.98,5,-5]],asset:'driving/school.webp'});
 // Destination bay has four physical edges; center is (85,62).
 this.rect(83.2,58.7,86.8,65.3,.026,'#577565');for(const [a,b,c,d] of [[83.1,58.7,83.2,65.3],[86.8,58.7,86.9,65.3],[83.1,58.6,86.9,58.7]])this.rect(a,b,c,d,.04,'#f2e2ac');
 this.mesh.push({label:'P',x:85,y:.07,z:61.8,size:1.5,color:'#eaf2de',ground:true});
 for(const b of route.buildings){this.box(b.x,0,b.z,b.w,b.h,b.d,b.style==='pizza'?['#a3513f','#874633','#a3513f','#e3c59d']:['#d1c9af','#a5aa9b','#ddd4bc','#e5ded0']);if(b.asset){let pts=b.x<0?[[b.x+b.w/2+.02,0,b.z-b.d/2],[b.x+b.w/2+.02,0,b.z+b.d/2],[b.x+b.w/2+.02,b.h,b.z+b.d/2],[b.x+b.w/2+.02,b.h,b.z-b.d/2]]:[[b.x-b.w/2,0,b.z+b.d/2+.02],[b.x+b.w/2,0,b.z+b.d/2+.02],[b.x+b.w/2,b.h,b.z+b.d/2+.02],[b.x-b.w/2,b.h,b.z+b.d/2+.02]];this.mesh.push({points:pts,asset:b.asset});}else{
 // Same red brick, cream fascia, striped red awning and glazed frontage as pizza-shop.js.
 this.box(b.x-b.w/2-.04,2.1,b.z,.12,1,b.d,'#e8d8ad');for(let z=b.z-4;z<=b.z+4;z+=2)this.box(b.x-b.w/2-.13,.3,z,.09,1.8,1.4,['#244956','#35596b','#315567','#a3bec0']);this.mesh.push({label:'PIZZA CO.',x:b.x-b.w/2-.3,y:4.3,z:b.z,size:1.3,color:'#fbe7bc'});
 }}
 for(const s of [{x:7.5,z:70,type:'stop'},{x:7.8,z:25,type:'speed'},{x:8,z:62,type:'crossing'},{x:63,z:72,type:'parking'}]){this.box(s.x,0,s.z,.11,2.65,.11,'#8d999a');this.mesh.push({...s,y:3.3,sign:true});}
 for(let z=-15;z<111;z+=13){for(const x of [-10,10]){if(x===-10&&z<25||Math.abs(z-80)<14)continue;this.box(x,0,z,.3,2.4,.3,'#726147');this.mesh.push({tree:true,x,y:3.2,z,size:2.2,color:'#39755a'});}}
 for(let x=20;x<110;x+=15){this.box(x,0,91,.3,2.4,.3,'#736347');this.mesh.push({tree:true,x,y:3.2,z:91,size:2.2,color:'#448065'});}
 // Static parked car adjacent to training bay, represented in all views.
 }
 camera(s,yaw,w,h){return {x:s.x,z:s.z,y:1.28,yaw,f:Math.min(w*.79,h*1.65),cx:w/2,cy:h*.40,w,h};}
 transform(p,c){const dx=p[0]-c.x,dz=p[2]-c.z;return [dx*Math.cos(c.yaw)-dz*Math.sin(c.yaw),p[1]-c.y,dx*Math.sin(c.yaw)+dz*Math.cos(c.yaw)];}
 project(p,c){return {x:c.cx+p[0]*c.f/p[2],y:c.cy-p[1]*c.f/p[2],z:p[2]};}
 clip(points){let out=[];for(let i=0;i<points.length;i++){let a=points[i],b=points[(i+1)%points.length],ai=a[2]>=.35,bi=b[2]>=.35;if(ai)out.push(a);if(ai!==bi){let t=(.35-a[2])/(b[2]-a[2]);out.push([a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t,.35]);}}return out;}
 dynamic(lesson){const t=lesson.traffic;const list=[];const cube=(cx,cy,cz,w,h,d,color)=>{const pts=[[-w/2,cy,-d/2],[w/2,cy,-d/2],[w/2,cy+h,-d/2],[-w/2,cy+h,-d/2],[-w/2,cy,d/2],[w/2,cy,d/2],[w/2,cy+h,d/2],[-w/2,cy+h,d/2]].map(([x,y,z])=>[cx+x*Math.cos(t.yaw)+z*Math.sin(t.yaw),y,cz-x*Math.sin(t.yaw)+z*Math.cos(t.yaw)]);for(const [idx,col] of [[[0,1,2,3],color],[[1,5,6,2],'#a86842'],[[5,4,7,6],color],[[4,0,3,7],'#c88755'],[[3,2,6,7],'#dea778']])list.push({points:idx.map(i=>pts[i]),color:col});};cube(t.x,.28,t.z,1.85,.65,4.2,'#cd824f');cube(t.x, .92,t.z-.2,1.58,.62,2.1,'#355263');cube(t.x,.07,t.z,1.8,.25,3.5,'#1b242a');
 if(lesson.ped.active||lesson.ped.done){const p=lesson.ped,step=Math.sin(lesson.state.t*7)*.17;list.push({points:[[p.x-.19,.75,p.z],[p.x+.19,.75,p.z],[p.x+.25,1.45,p.z],[p.x-.25,1.45,p.z]],color:'#ba6686'}, {points:[[p.x-.18,.05,p.z],[p.x-.03,.05,p.z],[p.x-.01,.85,p.z],[p.x-.17,.85,p.z]],color:'#293b54'},{points:[[p.x+.03,.05,p.z+step],[p.x+.18,.05,p.z+step],[p.x+.17,.85,p.z],[p.x+.01,.85,p.z]],color:'#293b54'},{tree:true,x:p.x,y:1.64,z:p.z,size:.19,color:'#b87c5b',person:true});}return list;}
 triangle(ctx,img,a,b,c,ua,ub,uc){const den=ua.x*(ub.y-uc.y)+ub.x*(uc.y-ua.y)+uc.x*(ua.y-ub.y);if(Math.abs(den)<.001)return;const solve=k=>[(a[k]*(ub.y-uc.y)+b[k]*(uc.y-ua.y)+c[k]*(ua.y-ub.y))/den,(a[k]*(uc.x-ub.x)+b[k]*(ua.x-uc.x)+c[k]*(ub.x-ua.x))/den,(a[k]*(ub.x*uc.y-uc.x*ub.y)+b[k]*(uc.x*ua.y-ua.x*uc.y)+c[k]*(ua.x*ub.y-ub.x*ua.y))/den];let x=solve('x'),y=solve('y');ctx.save();ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineTo(c.x,c.y);ctx.closePath();ctx.clip();ctx.setTransform(x[0],y[0],x[1],y[1],x[2],y[2]);ctx.drawImage(img,0,0);ctx.restore();}
 render(lesson,canvas,yaw,mirror=false){let ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;let s=lesson.state,c=this.camera(s,yaw,w,h);ctx.setTransform(1,0,0,1,0,0);const sky=ctx.createLinearGradient(0,0,0,h*.48);sky.addColorStop(0,'#7cafc8');sky.addColorStop(1,'#dae8df');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);ctx.fillStyle='#7d9d79';ctx.fillRect(0,c.cy,w,h-c.cy);ctx.fillStyle='#9cb5a3';ctx.beginPath();ctx.moveTo(0,c.cy);for(let i=0;i<=12;i++)ctx.lineTo(i*w/12,c.cy-10-8*Math.sin(i*1.3+yaw));ctx.lineTo(w,c.cy);ctx.fill();
 let queue=[];for(const o of this.mesh.concat(this.dynamic(lesson))){if(o.points){let raw=o.points.map(p=>this.transform(p,c));if(raw.every(p=>p[2]<.35)||raw.every(p=>p[2]>170))continue;let pts=this.clip(raw).map(p=>this.project(p,c));if(pts.length<3)continue;queue.push({...o,pts,raw,depth:raw.reduce((n,p)=>n+p[2],0)/raw.length});}else{let p=this.transform([o.x,o.y,o.z],c);if(p[2]>.5&&p[2]<170)queue.push({...o,p:this.project(p,c),depth:p[2]});}}queue.sort((a,b)=>(a.layer??2)-(b.layer??2)||b.depth-a.depth);
 for(const o of queue){if(o.pts){ctx.fillStyle=o.color||'#bec9bc';ctx.beginPath();o.pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fill();if(o.asset&&this.images[o.asset]&&o.raw.every(p=>p[2]>.35)){const img=this.images[o.asset],p=o.pts,uv=[{x:0,y:img.height},{x:img.width,y:img.height},{x:img.width,y:0},{x:0,y:0}];this.triangle(ctx,img,p[0],p[1],p[2],uv[0],uv[1],uv[2]);this.triangle(ctx,img,p[0],p[2],p[3],uv[0],uv[2],uv[3]);}}else{let p=o.p,scale=c.f/p.z;if(p.x<-100||p.x>w+100)continue;if(o.tree){ctx.fillStyle=o.color;ctx.beginPath();ctx.ellipse(p.x,p.y,o.size*scale,o.size*scale*(o.person?1:1.1),0,0,Math.PI*2);ctx.fill();if(!o.person){ctx.fillStyle='#58916a';ctx.beginPath();ctx.arc(p.x-o.size*scale*.25,p.y-o.size*scale*.25,o.size*scale*.6,0,Math.PI*2);ctx.fill();}}else if(o.sign)this.sign(ctx,o,p,scale);else if(o.label){ctx.fillStyle=o.color;ctx.font='600 '+Math.max(7,o.size*scale)+'px system-ui';ctx.textAlign='center';ctx.fillText(o.label,p.x,p.y);}}}
 if(mirror){const snapshot=this.mirrorBuffer;if(snapshot.width!==w)snapshot.width=w;if(snapshot.height!==h)snapshot.height=h;snapshot.getContext('2d').drawImage(canvas,0,0);ctx.save();ctx.translate(w,0);ctx.scale(-1,1);ctx.drawImage(snapshot,0,0);ctx.restore();}
 }
 sign(ctx,o,p,k){let r=.65*k;ctx.save();ctx.translate(p.x,p.y);if(o.type==='stop'){ctx.fillStyle='#b84032';ctx.strokeStyle='#f2e9d7';ctx.lineWidth=Math.max(1,k*.06);ctx.beginPath();for(let i=0;i<8;i++){let a=Math.PI/8+i*Math.PI/4;let x=Math.cos(a)*r,y=Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#fff5e7';ctx.font='bold '+r*.47+'px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('STOP',0,0);}else{ctx.fillStyle=o.type==='crossing'?'#e5c052':o.type==='parking'?'#497b64':'#f1efe2';ctx.fillRect(-r,-r,r*2,r*2.4);ctx.fillStyle=o.type==='parking'?'#fff':'#233640';ctx.textAlign='center';ctx.font='bold '+r*.7+'px Arial';ctx.fillText(o.type==='speed'?'15':o.type==='parking'?'P':'WALK',0,r*.5);if(o.type==='speed'){ctx.font=r*.29+'px Arial';ctx.fillText('SPEED',0,-r*.45);ctx.fillText('LIMIT',0,-r*.1);}}ctx.restore();}
 draw(lesson){let s=lesson.state,yaw=s.yaw;if(lesson.look)yaw+=({left:-Math.PI/2,rear:Math.PI,right:Math.PI/2,shoulder:Math.PI})[lesson.look];this.render(lesson,this.canvas,yaw);}
 mirrors(lesson){const s=lesson.state;for(const [id,offset] of [['rearMirror',Math.PI],['leftMirror',-2.3],['rightMirror',2.3]])this.render(lesson,document.getElementById(id),s.yaw+offset,true);}
 map(lesson){let c=document.getElementById('map'),ctx=c.getContext('2d'),sx=x=>(x+43)*1.25,sy=z=>170-(z+20)*1.25;ctx.clearRect(0,0,200,180);ctx.fillStyle='#667378';for(const [a,b,d,e] of route.paved)ctx.fillRect(sx(a),sy(e),(d-a)*1.25,(e-b)*1.25);ctx.strokeStyle='#d6bd82';ctx.lineWidth=2;ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(sx(-12),sy(8));ctx.lineTo(sx(3),sy(8));ctx.lineTo(sx(3),sy(77));ctx.lineTo(sx(85),sy(77));ctx.lineTo(sx(85),sy(62));ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#b6daab';ctx.fillRect(sx(82),sy(66),8,9);ctx.font='10px system-ui';ctx.fillStyle='#e7f1ed';ctx.fillText('GROCERY',sx(60),sy(39));ctx.fillText('STOP',sx(7),sy(67));let s=lesson.state;ctx.save();ctx.translate(sx(s.x),sy(s.z));ctx.rotate(s.yaw);ctx.fillStyle='#ffdda0';ctx.beginPath();ctx.moveTo(0,-6);ctx.lineTo(-4,5);ctx.lineTo(4,5);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle='#e3a565';ctx.fillRect(sx(lesson.traffic.x)-3,sy(lesson.traffic.z)-2,6,4);if(lesson.ped.active){ctx.fillStyle='#ffa6c2';ctx.beginPath();ctx.arc(sx(lesson.ped.x),sy(74),2,0,7);ctx.fill();}}
}
window.TTDrivingRenderer=Renderer;
})();
